/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAgentStaking,
  IAgentStakingInterface,
} from "../../../contracts/interfaces/IAgentStaking";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "agent",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "creditEarnings",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "agent",
        type: "address",
      },
    ],
    name: "isStaked",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IAgentStaking__factory {
  static readonly abi = _abi;
  static createInterface(): IAgentStakingInterface {
    return new Interface(_abi) as IAgentStakingInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IAgentStaking {
    return new Contract(address, _abi, runner) as unknown as IAgentStaking;
  }
}
