/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IFastUpdater,
  IFastUpdaterInterface,
} from "../../../contracts/interfaces/IFastUpdater";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256[]",
        name: "_feedIndexes",
        type: "uint256[]",
      },
    ],
    name: "fetchCurrentFeeds",
    outputs: [
      {
        internalType: "uint256[]",
        name: "_feeds",
        type: "uint256[]",
      },
      {
        internalType: "int8[]",
        name: "_decimals",
        type: "int8[]",
      },
      {
        internalType: "int64",
        name: "_timestamp",
        type: "int64",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IFastUpdater__factory {
  static readonly abi = _abi;
  static createInterface(): IFastUpdaterInterface {
    return new Interface(_abi) as IFastUpdaterInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IFastUpdater {
    return new Contract(address, _abi, runner) as unknown as IFastUpdater;
  }
}
