/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IFdcHub,
  IFdcHubInterface,
} from "../../../contracts/interfaces/IFdcHub";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "requestAttestation",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class IFdcHub__factory {
  static readonly abi = _abi;
  static createInterface(): IFdcHubInterface {
    return new Interface(_abi) as IFdcHubInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IFdcHub {
    return new Contract(address, _abi, runner) as unknown as IFdcHub;
  }
}
