/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IFdcVerification,
  IFdcVerificationInterface,
} from "../../../contracts/interfaces/IFdcVerification";

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            internalType: "bytes32[]",
            name: "merkleProof",
            type: "bytes32[]",
          },
          {
            components: [
              {
                internalType: "bytes32",
                name: "attestationType",
                type: "bytes32",
              },
              {
                internalType: "bytes32",
                name: "sourceId",
                type: "bytes32",
              },
              {
                internalType: "uint64",
                name: "votingRound",
                type: "uint64",
              },
              {
                internalType: "uint64",
                name: "lowestUsedTimestamp",
                type: "uint64",
              },
              {
                components: [
                  {
                    internalType: "string",
                    name: "url",
                    type: "string",
                  },
                  {
                    internalType: "string",
                    name: "postprocessJq",
                    type: "string",
                  },
                  {
                    internalType: "string",
                    name: "headerKey",
                    type: "string",
                  },
                  {
                    internalType: "string",
                    name: "headerValue",
                    type: "string",
                  },
                ],
                internalType: "struct IJsonApi.Request",
                name: "requestBody",
                type: "tuple",
              },
              {
                components: [
                  {
                    internalType: "bytes",
                    name: "abiEncodedData",
                    type: "bytes",
                  },
                ],
                internalType: "struct IJsonApi.Response",
                name: "responseBody",
                type: "tuple",
              },
            ],
            internalType: "struct IJsonApi.Body",
            name: "body",
            type: "tuple",
          },
        ],
        internalType: "struct IJsonApi.Proof",
        name: "proof",
        type: "tuple",
      },
    ],
    name: "verifyJsonApi",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IFdcVerification__factory {
  static readonly abi = _abi;
  static createInterface(): IFdcVerificationInterface {
    return new Interface(_abi) as IFdcVerificationInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IFdcVerification {
    return new Contract(address, _abi, runner) as unknown as IFdcVerification;
  }
}
