/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IFlareContractRegistry,
  IFlareContractRegistryInterface,
} from "../../../contracts/interfaces/IFlareContractRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "name",
        type: "string",
      },
    ],
    name: "getContractAddressByName",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IFlareContractRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IFlareContractRegistryInterface {
    return new Interface(_abi) as IFlareContractRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IFlareContractRegistry {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IFlareContractRegistry;
  }
}
