/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IRandomNumberV2,
  IRandomNumberV2Interface,
} from "../../../contracts/interfaces/IRandomNumberV2";

const _abi = [
  {
    inputs: [],
    name: "getRandomNumber",
    outputs: [
      {
        internalType: "uint256",
        name: "_randomNumber",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "_isSecureRandom",
        type: "bool",
      },
      {
        internalType: "uint256",
        name: "_randomTimestamp",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IRandomNumberV2__factory {
  static readonly abi = _abi;
  static createInterface(): IRandomNumberV2Interface {
    return new Interface(_abi) as IRandomNumberV2Interface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IRandomNumberV2 {
    return new Contract(address, _abi, runner) as unknown as IRandomNumberV2;
  }
}
