/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  MockFdcVerification,
  MockFdcVerificationInterface,
} from "../../../contracts/mocks/MockFdcVerification";

const _abi = [
  {
    inputs: [
      {
        internalType: "bool",
        name: "pass",
        type: "bool",
      },
    ],
    name: "setShouldPass",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "shouldPass",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "bytes32[]",
            name: "merkleProof",
            type: "bytes32[]",
          },
          {
            components: [
              {
                internalType: "bytes32",
                name: "attestationType",
                type: "bytes32",
              },
              {
                internalType: "bytes32",
                name: "sourceId",
                type: "bytes32",
              },
              {
                internalType: "uint64",
                name: "votingRound",
                type: "uint64",
              },
              {
                internalType: "uint64",
                name: "lowestUsedTimestamp",
                type: "uint64",
              },
              {
                components: [
                  {
                    internalType: "string",
                    name: "url",
                    type: "string",
                  },
                  {
                    internalType: "string",
                    name: "postprocessJq",
                    type: "string",
                  },
                  {
                    internalType: "string",
                    name: "headerKey",
                    type: "string",
                  },
                  {
                    internalType: "string",
                    name: "headerValue",
                    type: "string",
                  },
                ],
                internalType: "struct IJsonApi.Request",
                name: "requestBody",
                type: "tuple",
              },
              {
                components: [
                  {
                    internalType: "bytes",
                    name: "abiEncodedData",
                    type: "bytes",
                  },
                ],
                internalType: "struct IJsonApi.Response",
                name: "responseBody",
                type: "tuple",
              },
            ],
            internalType: "struct IJsonApi.Body",
            name: "body",
            type: "tuple",
          },
        ],
        internalType: "struct IJsonApi.Proof",
        name: "",
        type: "tuple",
      },
    ],
    name: "verifyJsonApi",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60806040526000805460ff1916600117905534801561001d57600080fd5b5061012b8061002d6000396000f3fe6080604052348015600f57600080fd5b5060043610603c5760003560e01c806367607372146041578063c596f469146061578063eb5dd1e314608a575b600080fd5b605f604c3660046096565b6000805460ff1916911515919091179055565b005b6076606c36600460bd565b5060005460ff1690565b604051901515815260200160405180910390f35b60005460769060ff1681565b60006020828403121560a757600080fd5b8135801515811460b657600080fd5b9392505050565b60006020828403121560ce57600080fd5b813567ffffffffffffffff81111560e457600080fd5b82016040818503121560b657600080fdfea2646970667358221220ca4e62537e66c4de786814585035e467a267c80700948a0b2fb4192a136c6d0364736f6c63430008180033";

type MockFdcVerificationConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockFdcVerificationConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockFdcVerification__factory extends ContractFactory {
  constructor(...args: MockFdcVerificationConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MockFdcVerification & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): MockFdcVerification__factory {
    return super.connect(runner) as MockFdcVerification__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockFdcVerificationInterface {
    return new Interface(_abi) as MockFdcVerificationInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MockFdcVerification {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as MockFdcVerification;
  }
}
