/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  MockFastUpdater,
  MockFastUpdaterInterface,
} from "../../../contracts/mocks/MockFastUpdater";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256[]",
        name: "_feedIndexes",
        type: "uint256[]",
      },
    ],
    name: "fetchCurrentFeeds",
    outputs: [
      {
        internalType: "uint256[]",
        name: "feeds",
        type: "uint256[]",
      },
      {
        internalType: "int8[]",
        name: "decimals",
        type: "int8[]",
      },
      {
        internalType: "int64",
        name: "timestamp",
        type: "int64",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "feedIndex",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "price",
        type: "uint256",
      },
      {
        internalType: "int8",
        name: "decimals_",
        type: "int8",
      },
    ],
    name: "setPrice",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b5061039d806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c80632ebaa8201461003b57806345a15d3c14610077575b600080fd5b6100756100493660046101f6565b60009283526020838152604080852093909355600190529120805460ff191660ff909216919091179055565b005b61008a610085366004610235565b6100a2565b604051610099939291906102aa565b60405180910390f35b60608060008367ffffffffffffffff8111156100c0576100c061033b565b6040519080825280602002602001820160405280156100e9578160200160208202803683370190505b5092508367ffffffffffffffff8111156101055761010561033b565b60405190808252806020026020018201604052801561012e578160200160208202803683370190505b50915060005b848110156101eb5760008087878481811061015157610151610351565b9050602002013581526020019081526020016000205484828151811061017957610179610351565b6020026020010181815250506001600087878481811061019b5761019b610351565b90506020020135815260200190815260200160002060009054906101000a900460000b8382815181106101d0576101d0610351565b60009290920b60209283029190910190910152600101610134565b504290509250925092565b60008060006060848603121561020b57600080fd5b833592506020840135915060408401358060000b811461022a57600080fd5b809150509250925092565b6000806020838503121561024857600080fd5b823567ffffffffffffffff8082111561026057600080fd5b818501915085601f83011261027457600080fd5b81358181111561028357600080fd5b8660208260051b850101111561029857600080fd5b60209290920196919550909350505050565b60608082528451908201819052600090602090608084019082880184805b838110156102e4578251855293850193918501916001016102c8565b508684038588015288518085528986019486019350915060005b8281101561031c578451820b845293850193928501926001016102fe565b505050600786900b60408601529250610333915050565b949350505050565b634e487b7160e01b600052604160045260246000fd5b634e487b7160e01b600052603260045260246000fdfea2646970667358221220fd5b90139f1d6c90cd755c58ab2df7ccd0335526677f1fd8e68f85c4ebb60c8364736f6c63430008180033";

type MockFastUpdaterConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockFastUpdaterConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockFastUpdater__factory extends ContractFactory {
  constructor(...args: MockFastUpdaterConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MockFastUpdater & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): MockFastUpdater__factory {
    return super.connect(runner) as MockFastUpdater__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockFastUpdaterInterface {
    return new Interface(_abi) as MockFastUpdaterInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MockFastUpdater {
    return new Contract(address, _abi, runner) as unknown as MockFastUpdater;
  }
}
