/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace JobTypes {
  export type BidMetadataStruct = {
    id: BigNumberish;
    jobId: BigNumberish;
    bidder: AddressLike;
    price: BigNumberish;
    deliveryTime: BigNumberish;
    reputation: BigNumberish;
    metadataURI: string;
    accepted: boolean;
    createdAt: BigNumberish;
  };

  export type BidMetadataStructOutput = [
    id: bigint,
    jobId: bigint,
    bidder: string,
    price: bigint,
    deliveryTime: bigint,
    reputation: bigint,
    metadataURI: string,
    accepted: boolean,
    createdAt: bigint
  ] & {
    id: bigint;
    jobId: bigint;
    bidder: string;
    price: bigint;
    deliveryTime: bigint;
    reputation: bigint;
    metadataURI: string;
    accepted: boolean;
    createdAt: bigint;
  };

  export type DeliveryReceiptStruct = {
    jobId: BigNumberish;
    proofHash: BytesLike;
    deliveredAt: BigNumberish;
  };

  export type DeliveryReceiptStructOutput = [
    jobId: bigint,
    proofHash: string,
    deliveredAt: bigint
  ] & { jobId: bigint; proofHash: string; deliveredAt: bigint };

  export type JobMetadataStruct = {
    id: BigNumberish;
    poster: AddressLike;
    description: string;
    metadataURI: string;
    tags: string[];
    deadline: BigNumberish;
    createdAt: BigNumberish;
  };

  export type JobMetadataStructOutput = [
    id: bigint,
    poster: string,
    description: string,
    metadataURI: string,
    tags: string[],
    deadline: bigint,
    createdAt: bigint
  ] & {
    id: bigint;
    poster: string;
    description: string;
    metadataURI: string;
    tags: string[];
    deadline: bigint;
    createdAt: bigint;
  };
}

export interface IJobRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "indexBid"
      | "indexDelivery"
      | "updateJobStatus"
      | "upsertJob"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "indexBid",
    values: [JobTypes.BidMetadataStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "indexDelivery",
    values: [JobTypes.DeliveryReceiptStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "updateJobStatus",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "upsertJob",
    values: [JobTypes.JobMetadataStruct, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "indexBid", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "indexDelivery",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateJobStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "upsertJob", data: BytesLike): Result;
}

export interface IJobRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IJobRegistry;
  waitForDeployment(): Promise<this>;

  interface: IJobRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  indexBid: TypedContractMethod<
    [bid: JobTypes.BidMetadataStruct],
    [void],
    "nonpayable"
  >;

  indexDelivery: TypedContractMethod<
    [receipt: JobTypes.DeliveryReceiptStruct],
    [void],
    "nonpayable"
  >;

  updateJobStatus: TypedContractMethod<
    [jobId: BigNumberish, status: BigNumberish],
    [void],
    "nonpayable"
  >;

  upsertJob: TypedContractMethod<
    [job: JobTypes.JobMetadataStruct, status: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "indexBid"
  ): TypedContractMethod<
    [bid: JobTypes.BidMetadataStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "indexDelivery"
  ): TypedContractMethod<
    [receipt: JobTypes.DeliveryReceiptStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateJobStatus"
  ): TypedContractMethod<
    [jobId: BigNumberish, status: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "upsertJob"
  ): TypedContractMethod<
    [job: JobTypes.JobMetadataStruct, status: BigNumberish],
    [void],
    "nonpayable"
  >;

  filters: {};
}
