/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace OrderBook {
  export type DisputeStruct = {
    disputeId: BigNumberish;
    jobId: BigNumberish;
    initiator: AddressLike;
    reason: string;
    evidence: string[];
    status: BigNumberish;
    resolutionMessage: string;
    createdAt: BigNumberish;
    resolvedAt: BigNumberish;
  };

  export type DisputeStructOutput = [
    disputeId: bigint,
    jobId: bigint,
    initiator: string,
    reason: string,
    evidence: string[],
    status: bigint,
    resolutionMessage: string,
    createdAt: bigint,
    resolvedAt: bigint
  ] & {
    disputeId: bigint;
    jobId: bigint;
    initiator: string;
    reason: string;
    evidence: string[];
    status: bigint;
    resolutionMessage: string;
    createdAt: bigint;
    resolvedAt: bigint;
  };

  export type JobStateStruct = {
    poster: AddressLike;
    status: BigNumberish;
    acceptedBidId: BigNumberish;
    deliveryProof: BytesLike;
    hasDispute: boolean;
  };

  export type JobStateStructOutput = [
    poster: string,
    status: bigint,
    acceptedBidId: bigint,
    deliveryProof: string,
    hasDispute: boolean
  ] & {
    poster: string;
    status: bigint;
    acceptedBidId: bigint;
    deliveryProof: string;
    hasDispute: boolean;
  };

  export type BidStruct = {
    id: BigNumberish;
    jobId: BigNumberish;
    bidder: AddressLike;
    price: BigNumberish;
    deliveryTime: BigNumberish;
    reputation: BigNumberish;
    metadataURI: string;
    responseURI: string;
    accepted: boolean;
    createdAt: BigNumberish;
  };

  export type BidStructOutput = [
    id: bigint,
    jobId: bigint,
    bidder: string,
    price: bigint,
    deliveryTime: bigint,
    reputation: bigint,
    metadataURI: string,
    responseURI: string,
    accepted: boolean,
    createdAt: bigint
  ] & {
    id: bigint;
    jobId: bigint;
    bidder: string;
    price: bigint;
    deliveryTime: bigint;
    reputation: bigint;
    metadataURI: string;
    responseURI: string;
    accepted: boolean;
    createdAt: bigint;
  };
}

export interface OrderBookInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptBid"
      | "agentRegistry"
      | "approveDelivery"
      | "escrow"
      | "getDispute"
      | "getJob"
      | "getJobDispute"
      | "jobRegistry"
      | "owner"
      | "placeBid"
      | "postJob"
      | "raiseDispute"
      | "refundJob"
      | "renounceOwnership"
      | "reputationToken"
      | "resolveDispute"
      | "setAgentRegistry"
      | "setEscrow"
      | "setReputationToken"
      | "submitDelivery"
      | "submitEvidence"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BidAccepted"
      | "BidPlaced"
      | "BidResponseSubmitted"
      | "DeliverySubmitted"
      | "DisputeRaised"
      | "DisputeResolved"
      | "EvidenceSubmitted"
      | "JobApproved"
      | "JobPosted"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptBid",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "agentRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "approveDelivery",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "escrow", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getDispute",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getJob",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getJobDispute",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "jobRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "placeBid",
    values: [BigNumberish, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "postJob",
    values: [string, string, string[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "raiseDispute",
    values: [BigNumberish, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "refundJob",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reputationToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resolveDispute",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setAgentRegistry",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setEscrow",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setReputationToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitDelivery",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitEvidence",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "acceptBid", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "agentRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approveDelivery",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "escrow", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getDispute", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getJob", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getJobDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "jobRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "placeBid", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "postJob", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "raiseDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "refundJob", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reputationToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAgentRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setEscrow", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setReputationToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitDelivery",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitEvidence",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace BidAcceptedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    bidId: BigNumberish,
    poster: AddressLike,
    agent: AddressLike
  ];
  export type OutputTuple = [
    jobId: bigint,
    bidId: bigint,
    poster: string,
    agent: string
  ];
  export interface OutputObject {
    jobId: bigint;
    bidId: bigint;
    poster: string;
    agent: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BidPlacedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    bidId: BigNumberish,
    bidder: AddressLike,
    price: BigNumberish
  ];
  export type OutputTuple = [
    jobId: bigint,
    bidId: bigint,
    bidder: string,
    price: bigint
  ];
  export interface OutputObject {
    jobId: bigint;
    bidId: bigint;
    bidder: string;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BidResponseSubmittedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    bidId: BigNumberish,
    responseURI: string
  ];
  export type OutputTuple = [jobId: bigint, bidId: bigint, responseURI: string];
  export interface OutputObject {
    jobId: bigint;
    bidId: bigint;
    responseURI: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DeliverySubmittedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    bidId: BigNumberish,
    proofHash: BytesLike
  ];
  export type OutputTuple = [jobId: bigint, bidId: bigint, proofHash: string];
  export interface OutputObject {
    jobId: bigint;
    bidId: bigint;
    proofHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeRaisedEvent {
  export type InputTuple = [
    disputeId: BigNumberish,
    jobId: BigNumberish,
    initiator: AddressLike,
    reason: string
  ];
  export type OutputTuple = [
    disputeId: bigint,
    jobId: bigint,
    initiator: string,
    reason: string
  ];
  export interface OutputObject {
    disputeId: bigint;
    jobId: bigint;
    initiator: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeResolvedEvent {
  export type InputTuple = [
    disputeId: BigNumberish,
    jobId: BigNumberish,
    resolution: BigNumberish,
    message: string
  ];
  export type OutputTuple = [
    disputeId: bigint,
    jobId: bigint,
    resolution: bigint,
    message: string
  ];
  export interface OutputObject {
    disputeId: bigint;
    jobId: bigint;
    resolution: bigint;
    message: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EvidenceSubmittedEvent {
  export type InputTuple = [
    disputeId: BigNumberish,
    submitter: AddressLike,
    evidence: string
  ];
  export type OutputTuple = [
    disputeId: bigint,
    submitter: string,
    evidence: string
  ];
  export interface OutputObject {
    disputeId: bigint;
    submitter: string;
    evidence: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobApprovedEvent {
  export type InputTuple = [jobId: BigNumberish, bidId: BigNumberish];
  export type OutputTuple = [jobId: bigint, bidId: bigint];
  export interface OutputObject {
    jobId: bigint;
    bidId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobPostedEvent {
  export type InputTuple = [jobId: BigNumberish, poster: AddressLike];
  export type OutputTuple = [jobId: bigint, poster: string];
  export interface OutputObject {
    jobId: bigint;
    poster: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface OrderBook extends BaseContract {
  connect(runner?: ContractRunner | null): OrderBook;
  waitForDeployment(): Promise<this>;

  interface: OrderBookInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptBid: TypedContractMethod<
    [jobId: BigNumberish, bidId: BigNumberish, responseURI: string],
    [void],
    "nonpayable"
  >;

  agentRegistry: TypedContractMethod<[], [string], "view">;

  approveDelivery: TypedContractMethod<
    [jobId: BigNumberish],
    [void],
    "nonpayable"
  >;

  escrow: TypedContractMethod<[], [string], "view">;

  getDispute: TypedContractMethod<
    [disputeId: BigNumberish],
    [OrderBook.DisputeStructOutput],
    "view"
  >;

  getJob: TypedContractMethod<
    [jobId: BigNumberish],
    [
      [OrderBook.JobStateStructOutput, OrderBook.BidStructOutput[]] & {
        job: OrderBook.JobStateStructOutput;
        jobBids: OrderBook.BidStructOutput[];
      }
    ],
    "view"
  >;

  getJobDispute: TypedContractMethod<
    [jobId: BigNumberish],
    [OrderBook.DisputeStructOutput],
    "view"
  >;

  jobRegistry: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  placeBid: TypedContractMethod<
    [
      jobId: BigNumberish,
      price: BigNumberish,
      deliveryTime: BigNumberish,
      metadataURI: string
    ],
    [bigint],
    "nonpayable"
  >;

  postJob: TypedContractMethod<
    [
      description: string,
      metadataURI: string,
      tags: string[],
      deadline: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  raiseDispute: TypedContractMethod<
    [jobId: BigNumberish, reason: string, evidence: string],
    [bigint],
    "nonpayable"
  >;

  refundJob: TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  reputationToken: TypedContractMethod<[], [string], "view">;

  resolveDispute: TypedContractMethod<
    [disputeId: BigNumberish, resolution: BigNumberish, message: string],
    [void],
    "nonpayable"
  >;

  setAgentRegistry: TypedContractMethod<
    [registry: AddressLike],
    [void],
    "nonpayable"
  >;

  setEscrow: TypedContractMethod<
    [escrowAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  setReputationToken: TypedContractMethod<
    [reputationAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  submitDelivery: TypedContractMethod<
    [jobId: BigNumberish, proofHash: BytesLike],
    [void],
    "nonpayable"
  >;

  submitEvidence: TypedContractMethod<
    [disputeId: BigNumberish, evidence: string],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptBid"
  ): TypedContractMethod<
    [jobId: BigNumberish, bidId: BigNumberish, responseURI: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "agentRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "approveDelivery"
  ): TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "escrow"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getDispute"
  ): TypedContractMethod<
    [disputeId: BigNumberish],
    [OrderBook.DisputeStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getJob"
  ): TypedContractMethod<
    [jobId: BigNumberish],
    [
      [OrderBook.JobStateStructOutput, OrderBook.BidStructOutput[]] & {
        job: OrderBook.JobStateStructOutput;
        jobBids: OrderBook.BidStructOutput[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getJobDispute"
  ): TypedContractMethod<
    [jobId: BigNumberish],
    [OrderBook.DisputeStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "jobRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "placeBid"
  ): TypedContractMethod<
    [
      jobId: BigNumberish,
      price: BigNumberish,
      deliveryTime: BigNumberish,
      metadataURI: string
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "postJob"
  ): TypedContractMethod<
    [
      description: string,
      metadataURI: string,
      tags: string[],
      deadline: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "raiseDispute"
  ): TypedContractMethod<
    [jobId: BigNumberish, reason: string, evidence: string],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "refundJob"
  ): TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reputationToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "resolveDispute"
  ): TypedContractMethod<
    [disputeId: BigNumberish, resolution: BigNumberish, message: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAgentRegistry"
  ): TypedContractMethod<[registry: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setEscrow"
  ): TypedContractMethod<[escrowAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setReputationToken"
  ): TypedContractMethod<
    [reputationAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitDelivery"
  ): TypedContractMethod<
    [jobId: BigNumberish, proofHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitEvidence"
  ): TypedContractMethod<
    [disputeId: BigNumberish, evidence: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "BidAccepted"
  ): TypedContractEvent<
    BidAcceptedEvent.InputTuple,
    BidAcceptedEvent.OutputTuple,
    BidAcceptedEvent.OutputObject
  >;
  getEvent(
    key: "BidPlaced"
  ): TypedContractEvent<
    BidPlacedEvent.InputTuple,
    BidPlacedEvent.OutputTuple,
    BidPlacedEvent.OutputObject
  >;
  getEvent(
    key: "BidResponseSubmitted"
  ): TypedContractEvent<
    BidResponseSubmittedEvent.InputTuple,
    BidResponseSubmittedEvent.OutputTuple,
    BidResponseSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "DeliverySubmitted"
  ): TypedContractEvent<
    DeliverySubmittedEvent.InputTuple,
    DeliverySubmittedEvent.OutputTuple,
    DeliverySubmittedEvent.OutputObject
  >;
  getEvent(
    key: "DisputeRaised"
  ): TypedContractEvent<
    DisputeRaisedEvent.InputTuple,
    DisputeRaisedEvent.OutputTuple,
    DisputeRaisedEvent.OutputObject
  >;
  getEvent(
    key: "DisputeResolved"
  ): TypedContractEvent<
    DisputeResolvedEvent.InputTuple,
    DisputeResolvedEvent.OutputTuple,
    DisputeResolvedEvent.OutputObject
  >;
  getEvent(
    key: "EvidenceSubmitted"
  ): TypedContractEvent<
    EvidenceSubmittedEvent.InputTuple,
    EvidenceSubmittedEvent.OutputTuple,
    EvidenceSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "JobApproved"
  ): TypedContractEvent<
    JobApprovedEvent.InputTuple,
    JobApprovedEvent.OutputTuple,
    JobApprovedEvent.OutputObject
  >;
  getEvent(
    key: "JobPosted"
  ): TypedContractEvent<
    JobPostedEvent.InputTuple,
    JobPostedEvent.OutputTuple,
    JobPostedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "BidAccepted(uint256,uint256,address,address)": TypedContractEvent<
      BidAcceptedEvent.InputTuple,
      BidAcceptedEvent.OutputTuple,
      BidAcceptedEvent.OutputObject
    >;
    BidAccepted: TypedContractEvent<
      BidAcceptedEvent.InputTuple,
      BidAcceptedEvent.OutputTuple,
      BidAcceptedEvent.OutputObject
    >;

    "BidPlaced(uint256,uint256,address,uint256)": TypedContractEvent<
      BidPlacedEvent.InputTuple,
      BidPlacedEvent.OutputTuple,
      BidPlacedEvent.OutputObject
    >;
    BidPlaced: TypedContractEvent<
      BidPlacedEvent.InputTuple,
      BidPlacedEvent.OutputTuple,
      BidPlacedEvent.OutputObject
    >;

    "BidResponseSubmitted(uint256,uint256,string)": TypedContractEvent<
      BidResponseSubmittedEvent.InputTuple,
      BidResponseSubmittedEvent.OutputTuple,
      BidResponseSubmittedEvent.OutputObject
    >;
    BidResponseSubmitted: TypedContractEvent<
      BidResponseSubmittedEvent.InputTuple,
      BidResponseSubmittedEvent.OutputTuple,
      BidResponseSubmittedEvent.OutputObject
    >;

    "DeliverySubmitted(uint256,uint256,bytes32)": TypedContractEvent<
      DeliverySubmittedEvent.InputTuple,
      DeliverySubmittedEvent.OutputTuple,
      DeliverySubmittedEvent.OutputObject
    >;
    DeliverySubmitted: TypedContractEvent<
      DeliverySubmittedEvent.InputTuple,
      DeliverySubmittedEvent.OutputTuple,
      DeliverySubmittedEvent.OutputObject
    >;

    "DisputeRaised(uint256,uint256,address,string)": TypedContractEvent<
      DisputeRaisedEvent.InputTuple,
      DisputeRaisedEvent.OutputTuple,
      DisputeRaisedEvent.OutputObject
    >;
    DisputeRaised: TypedContractEvent<
      DisputeRaisedEvent.InputTuple,
      DisputeRaisedEvent.OutputTuple,
      DisputeRaisedEvent.OutputObject
    >;

    "DisputeResolved(uint256,uint256,uint8,string)": TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;
    DisputeResolved: TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;

    "EvidenceSubmitted(uint256,address,string)": TypedContractEvent<
      EvidenceSubmittedEvent.InputTuple,
      EvidenceSubmittedEvent.OutputTuple,
      EvidenceSubmittedEvent.OutputObject
    >;
    EvidenceSubmitted: TypedContractEvent<
      EvidenceSubmittedEvent.InputTuple,
      EvidenceSubmittedEvent.OutputTuple,
      EvidenceSubmittedEvent.OutputObject
    >;

    "JobApproved(uint256,uint256)": TypedContractEvent<
      JobApprovedEvent.InputTuple,
      JobApprovedEvent.OutputTuple,
      JobApprovedEvent.OutputObject
    >;
    JobApproved: TypedContractEvent<
      JobApprovedEvent.InputTuple,
      JobApprovedEvent.OutputTuple,
      JobApprovedEvent.OutputObject
    >;

    "JobPosted(uint256,address)": TypedContractEvent<
      JobPostedEvent.InputTuple,
      JobPostedEvent.OutputTuple,
      JobPostedEvent.OutputObject
    >;
    JobPosted: TypedContractEvent<
      JobPostedEvent.InputTuple,
      JobPostedEvent.OutputTuple,
      JobPostedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
