/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IJobRegistry,
  IJobRegistryInterface,
} from "../../../contracts/OrderBook.sol/IJobRegistry";

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "id",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "jobId",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "bidder",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "price",
            type: "uint256",
          },
          {
            internalType: "uint64",
            name: "deliveryTime",
            type: "uint64",
          },
          {
            internalType: "uint256",
            name: "reputation",
            type: "uint256",
          },
          {
            internalType: "string",
            name: "metadataURI",
            type: "string",
          },
          {
            internalType: "bool",
            name: "accepted",
            type: "bool",
          },
          {
            internalType: "uint256",
            name: "createdAt",
            type: "uint256",
          },
        ],
        internalType: "struct JobTypes.BidMetadata",
        name: "bid",
        type: "tuple",
      },
    ],
    name: "indexBid",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "jobId",
            type: "uint256",
          },
          {
            internalType: "bytes32",
            name: "proofHash",
            type: "bytes32",
          },
          {
            internalType: "uint256",
            name: "deliveredAt",
            type: "uint256",
          },
        ],
        internalType: "struct JobTypes.DeliveryReceipt",
        name: "receipt",
        type: "tuple",
      },
    ],
    name: "indexDelivery",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "jobId",
        type: "uint256",
      },
      {
        internalType: "enum JobTypes.JobStatus",
        name: "status",
        type: "uint8",
      },
    ],
    name: "updateJobStatus",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "id",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "poster",
            type: "address",
          },
          {
            internalType: "string",
            name: "description",
            type: "string",
          },
          {
            internalType: "string",
            name: "metadataURI",
            type: "string",
          },
          {
            internalType: "string[]",
            name: "tags",
            type: "string[]",
          },
          {
            internalType: "uint64",
            name: "deadline",
            type: "uint64",
          },
          {
            internalType: "uint256",
            name: "createdAt",
            type: "uint256",
          },
        ],
        internalType: "struct JobTypes.JobMetadata",
        name: "job",
        type: "tuple",
      },
      {
        internalType: "enum JobTypes.JobStatus",
        name: "status",
        type: "uint8",
      },
    ],
    name: "upsertJob",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IJobRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IJobRegistryInterface {
    return new Interface(_abi) as IJobRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IJobRegistry {
    return new Contract(address, _abi, runner) as unknown as IJobRegistry;
  }
}
