/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace AgentRegistry {
  export type AgentStruct = {
    name: string;
    metadataURI: string;
    capabilities: string[];
    reputation: BigNumberish;
    status: BigNumberish;
    createdAt: BigNumberish;
    updatedAt: BigNumberish;
  };

  export type AgentStructOutput = [
    name: string,
    metadataURI: string,
    capabilities: string[],
    reputation: bigint,
    status: bigint,
    createdAt: bigint,
    updatedAt: bigint
  ] & {
    name: string;
    metadataURI: string;
    capabilities: string[];
    reputation: bigint;
    status: bigint;
    createdAt: bigint;
    updatedAt: bigint;
  };
}

export interface AgentRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "adminUpdateStatus"
      | "agentCount"
      | "getAgent"
      | "getAgents"
      | "getAllAgents"
      | "isAgentActive"
      | "owner"
      | "registerAgent"
      | "renounceOwnership"
      | "reputationOracle"
      | "setReputationOracle"
      | "syncReputation"
      | "transferOwnership"
      | "updateAgent"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentRegistered"
      | "AgentUpdated"
      | "OwnershipTransferred"
      | "ReputationOracleUpdated"
      | "ReputationSynced"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "adminUpdateStatus",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "agentCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAgent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgents",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllAgents",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isAgentActive",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerAgent",
    values: [string, string, string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reputationOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setReputationOracle",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "syncReputation",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateAgent",
    values: [string, string, string[], BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "adminUpdateStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "agentCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getAgent", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getAgents", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllAgents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAgentActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reputationOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setReputationOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "syncReputation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateAgent",
    data: BytesLike
  ): Result;
}

export namespace AgentRegisteredEvent {
  export type InputTuple = [
    wallet: AddressLike,
    name: string,
    metadataURI: string
  ];
  export type OutputTuple = [wallet: string, name: string, metadataURI: string];
  export interface OutputObject {
    wallet: string;
    name: string;
    metadataURI: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentUpdatedEvent {
  export type InputTuple = [wallet: AddressLike, status: BigNumberish];
  export type OutputTuple = [wallet: string, status: bigint];
  export interface OutputObject {
    wallet: string;
    status: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReputationOracleUpdatedEvent {
  export type InputTuple = [oracle: AddressLike];
  export type OutputTuple = [oracle: string];
  export interface OutputObject {
    oracle: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReputationSyncedEvent {
  export type InputTuple = [wallet: AddressLike, reputation: BigNumberish];
  export type OutputTuple = [wallet: string, reputation: bigint];
  export interface OutputObject {
    wallet: string;
    reputation: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgentRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): AgentRegistry;
  waitForDeployment(): Promise<this>;

  interface: AgentRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  adminUpdateStatus: TypedContractMethod<
    [agent: AddressLike, status: BigNumberish],
    [void],
    "nonpayable"
  >;

  agentCount: TypedContractMethod<[], [bigint], "view">;

  getAgent: TypedContractMethod<
    [wallet: AddressLike],
    [AgentRegistry.AgentStructOutput],
    "view"
  >;

  getAgents: TypedContractMethod<
    [offset: BigNumberish, limit: BigNumberish],
    [
      [AgentRegistry.AgentStructOutput[], bigint] & {
        list: AgentRegistry.AgentStructOutput[];
        total: bigint;
      }
    ],
    "view"
  >;

  getAllAgents: TypedContractMethod<
    [],
    [AgentRegistry.AgentStructOutput[]],
    "view"
  >;

  isAgentActive: TypedContractMethod<[wallet: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  registerAgent: TypedContractMethod<
    [name: string, metadataURI: string, capabilities: string[]],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  reputationOracle: TypedContractMethod<[], [string], "view">;

  setReputationOracle: TypedContractMethod<
    [oracle: AddressLike],
    [void],
    "nonpayable"
  >;

  syncReputation: TypedContractMethod<
    [agent: AddressLike, reputation: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateAgent: TypedContractMethod<
    [
      name: string,
      metadataURI: string,
      capabilities: string[],
      status: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "adminUpdateStatus"
  ): TypedContractMethod<
    [agent: AddressLike, status: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "agentCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAgent"
  ): TypedContractMethod<
    [wallet: AddressLike],
    [AgentRegistry.AgentStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAgents"
  ): TypedContractMethod<
    [offset: BigNumberish, limit: BigNumberish],
    [
      [AgentRegistry.AgentStructOutput[], bigint] & {
        list: AgentRegistry.AgentStructOutput[];
        total: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAllAgents"
  ): TypedContractMethod<[], [AgentRegistry.AgentStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "isAgentActive"
  ): TypedContractMethod<[wallet: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerAgent"
  ): TypedContractMethod<
    [name: string, metadataURI: string, capabilities: string[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reputationOracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setReputationOracle"
  ): TypedContractMethod<[oracle: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "syncReputation"
  ): TypedContractMethod<
    [agent: AddressLike, reputation: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateAgent"
  ): TypedContractMethod<
    [
      name: string,
      metadataURI: string,
      capabilities: string[],
      status: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AgentRegistered"
  ): TypedContractEvent<
    AgentRegisteredEvent.InputTuple,
    AgentRegisteredEvent.OutputTuple,
    AgentRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "AgentUpdated"
  ): TypedContractEvent<
    AgentUpdatedEvent.InputTuple,
    AgentUpdatedEvent.OutputTuple,
    AgentUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ReputationOracleUpdated"
  ): TypedContractEvent<
    ReputationOracleUpdatedEvent.InputTuple,
    ReputationOracleUpdatedEvent.OutputTuple,
    ReputationOracleUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ReputationSynced"
  ): TypedContractEvent<
    ReputationSyncedEvent.InputTuple,
    ReputationSyncedEvent.OutputTuple,
    ReputationSyncedEvent.OutputObject
  >;

  filters: {
    "AgentRegistered(address,string,string)": TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;
    AgentRegistered: TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;

    "AgentUpdated(address,uint8)": TypedContractEvent<
      AgentUpdatedEvent.InputTuple,
      AgentUpdatedEvent.OutputTuple,
      AgentUpdatedEvent.OutputObject
    >;
    AgentUpdated: TypedContractEvent<
      AgentUpdatedEvent.InputTuple,
      AgentUpdatedEvent.OutputTuple,
      AgentUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ReputationOracleUpdated(address)": TypedContractEvent<
      ReputationOracleUpdatedEvent.InputTuple,
      ReputationOracleUpdatedEvent.OutputTuple,
      ReputationOracleUpdatedEvent.OutputObject
    >;
    ReputationOracleUpdated: TypedContractEvent<
      ReputationOracleUpdatedEvent.InputTuple,
      ReputationOracleUpdatedEvent.OutputTuple,
      ReputationOracleUpdatedEvent.OutputObject
    >;

    "ReputationSynced(address,uint256)": TypedContractEvent<
      ReputationSyncedEvent.InputTuple,
      ReputationSyncedEvent.OutputTuple,
      ReputationSyncedEvent.OutputObject
    >;
    ReputationSynced: TypedContractEvent<
      ReputationSyncedEvent.InputTuple,
      ReputationSyncedEvent.OutputTuple,
      ReputationSyncedEvent.OutputObject
    >;
  };
}
