/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace AgentStaking {
  export type StakeInfoStruct = {
    stakedAmount: BigNumberish;
    accumulatedEarnings: BigNumberish;
    wins: BigNumberish;
    losses: BigNumberish;
    isStaked: boolean;
  };

  export type StakeInfoStructOutput = [
    stakedAmount: bigint,
    accumulatedEarnings: bigint,
    wins: bigint,
    losses: bigint,
    isStaked: boolean
  ] & {
    stakedAmount: bigint;
    accumulatedEarnings: bigint;
    wins: bigint;
    losses: bigint;
    isStaked: boolean;
  };
}

export interface AgentStakingInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "agentRegistry"
      | "cashout"
      | "creditEarnings"
      | "escrow"
      | "getPoolSize"
      | "getStakeInfo"
      | "houseFeeBps"
      | "houseWallet"
      | "isStaked"
      | "lossPool"
      | "maxRandomAge"
      | "minimumStake"
      | "owner"
      | "previewCashout"
      | "randomNumberV2"
      | "renounceOwnership"
      | "seedPool"
      | "setEscrow"
      | "setHouseFeeBps"
      | "setHouseWallet"
      | "setMaxRandomAge"
      | "setMinimumStake"
      | "stake"
      | "stakes"
      | "transferOwnership"
      | "unstake"
      | "withdrawPool"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CashoutLoss"
      | "CashoutWin"
      | "EarningsCredited"
      | "EscrowUpdated"
      | "HouseFeePaid"
      | "HouseFeeUpdated"
      | "HouseWalletUpdated"
      | "MinimumStakeUpdated"
      | "OwnershipTransferred"
      | "PoolSeeded"
      | "PoolWithdrawn"
      | "Staked"
      | "Unstaked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "agentRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cashout",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "creditEarnings",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "escrow", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getPoolSize",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getStakeInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "houseFeeBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "houseWallet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isStaked",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "lossPool", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "maxRandomAge",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minimumStake",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "previewCashout",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "randomNumberV2",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "seedPool", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setEscrow",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setHouseFeeBps",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setHouseWallet",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxRandomAge",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMinimumStake",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "stake", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "stakes", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unstake",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawPool",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "agentRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cashout", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "creditEarnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "escrow", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPoolSize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStakeInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "houseFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "houseWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isStaked", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lossPool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "maxRandomAge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minimumStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "previewCashout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "randomNumberV2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "seedPool", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setEscrow", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setHouseFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setHouseWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxRandomAge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMinimumStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stake", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "stakes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unstake", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawPool",
    data: BytesLike
  ): Result;
}

export namespace CashoutLossEvent {
  export type InputTuple = [agent: AddressLike, lostEarnings: BigNumberish];
  export type OutputTuple = [agent: string, lostEarnings: bigint];
  export interface OutputObject {
    agent: string;
    lostEarnings: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CashoutWinEvent {
  export type InputTuple = [agent: AddressLike, payout: BigNumberish];
  export type OutputTuple = [agent: string, payout: bigint];
  export interface OutputObject {
    agent: string;
    payout: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EarningsCreditedEvent {
  export type InputTuple = [agent: AddressLike, amount: BigNumberish];
  export type OutputTuple = [agent: string, amount: bigint];
  export interface OutputObject {
    agent: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowUpdatedEvent {
  export type InputTuple = [escrow: AddressLike];
  export type OutputTuple = [escrow: string];
  export interface OutputObject {
    escrow: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HouseFeePaidEvent {
  export type InputTuple = [agent: AddressLike, amount: BigNumberish];
  export type OutputTuple = [agent: string, amount: bigint];
  export interface OutputObject {
    agent: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HouseFeeUpdatedEvent {
  export type InputTuple = [newFeeBps: BigNumberish];
  export type OutputTuple = [newFeeBps: bigint];
  export interface OutputObject {
    newFeeBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HouseWalletUpdatedEvent {
  export type InputTuple = [wallet: AddressLike];
  export type OutputTuple = [wallet: string];
  export interface OutputObject {
    wallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MinimumStakeUpdatedEvent {
  export type InputTuple = [newMinimum: BigNumberish];
  export type OutputTuple = [newMinimum: bigint];
  export interface OutputObject {
    newMinimum: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolSeededEvent {
  export type InputTuple = [from: AddressLike, amount: BigNumberish];
  export type OutputTuple = [from: string, amount: bigint];
  export interface OutputObject {
    from: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolWithdrawnEvent {
  export type InputTuple = [to: AddressLike, amount: BigNumberish];
  export type OutputTuple = [to: string, amount: bigint];
  export interface OutputObject {
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakedEvent {
  export type InputTuple = [agent: AddressLike, amount: BigNumberish];
  export type OutputTuple = [agent: string, amount: bigint];
  export interface OutputObject {
    agent: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnstakedEvent {
  export type InputTuple = [
    agent: AddressLike,
    amount: BigNumberish,
    forfeitedEarnings: BigNumberish
  ];
  export type OutputTuple = [
    agent: string,
    amount: bigint,
    forfeitedEarnings: bigint
  ];
  export interface OutputObject {
    agent: string;
    amount: bigint;
    forfeitedEarnings: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgentStaking extends BaseContract {
  connect(runner?: ContractRunner | null): AgentStaking;
  waitForDeployment(): Promise<this>;

  interface: AgentStakingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  agentRegistry: TypedContractMethod<[], [string], "view">;

  cashout: TypedContractMethod<[agent: AddressLike], [void], "nonpayable">;

  creditEarnings: TypedContractMethod<
    [agent: AddressLike, amount: BigNumberish],
    [void],
    "payable"
  >;

  escrow: TypedContractMethod<[], [string], "view">;

  getPoolSize: TypedContractMethod<[], [bigint], "view">;

  getStakeInfo: TypedContractMethod<
    [agent: AddressLike],
    [AgentStaking.StakeInfoStructOutput],
    "view"
  >;

  houseFeeBps: TypedContractMethod<[], [bigint], "view">;

  houseWallet: TypedContractMethod<[], [string], "view">;

  isStaked: TypedContractMethod<[agent: AddressLike], [boolean], "view">;

  lossPool: TypedContractMethod<[], [bigint], "view">;

  maxRandomAge: TypedContractMethod<[], [bigint], "view">;

  minimumStake: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  previewCashout: TypedContractMethod<
    [agent: AddressLike],
    [
      [bigint, bigint, bigint] & {
        earnings: bigint;
        houseFee: bigint;
        maxPayout: bigint;
      }
    ],
    "view"
  >;

  randomNumberV2: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  seedPool: TypedContractMethod<[], [void], "payable">;

  setEscrow: TypedContractMethod<[escrow_: AddressLike], [void], "nonpayable">;

  setHouseFeeBps: TypedContractMethod<
    [feeBps: BigNumberish],
    [void],
    "nonpayable"
  >;

  setHouseWallet: TypedContractMethod<
    [wallet: AddressLike],
    [void],
    "nonpayable"
  >;

  setMaxRandomAge: TypedContractMethod<
    [maxAge: BigNumberish],
    [void],
    "nonpayable"
  >;

  setMinimumStake: TypedContractMethod<
    [minimumStake_: BigNumberish],
    [void],
    "nonpayable"
  >;

  stake: TypedContractMethod<[agent: AddressLike], [void], "payable">;

  stakes: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        stakedAmount: bigint;
        accumulatedEarnings: bigint;
        wins: bigint;
        losses: bigint;
        isStaked: boolean;
      }
    ],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unstake: TypedContractMethod<[agent: AddressLike], [void], "nonpayable">;

  withdrawPool: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "agentRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "cashout"
  ): TypedContractMethod<[agent: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "creditEarnings"
  ): TypedContractMethod<
    [agent: AddressLike, amount: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "escrow"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getPoolSize"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getStakeInfo"
  ): TypedContractMethod<
    [agent: AddressLike],
    [AgentStaking.StakeInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "houseFeeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "houseWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "isStaked"
  ): TypedContractMethod<[agent: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "lossPool"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "maxRandomAge"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "minimumStake"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "previewCashout"
  ): TypedContractMethod<
    [agent: AddressLike],
    [
      [bigint, bigint, bigint] & {
        earnings: bigint;
        houseFee: bigint;
        maxPayout: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "randomNumberV2"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "seedPool"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "setEscrow"
  ): TypedContractMethod<[escrow_: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setHouseFeeBps"
  ): TypedContractMethod<[feeBps: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setHouseWallet"
  ): TypedContractMethod<[wallet: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMaxRandomAge"
  ): TypedContractMethod<[maxAge: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMinimumStake"
  ): TypedContractMethod<[minimumStake_: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stake"
  ): TypedContractMethod<[agent: AddressLike], [void], "payable">;
  getFunction(
    nameOrSignature: "stakes"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        stakedAmount: bigint;
        accumulatedEarnings: bigint;
        wins: bigint;
        losses: bigint;
        isStaked: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unstake"
  ): TypedContractMethod<[agent: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawPool"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "CashoutLoss"
  ): TypedContractEvent<
    CashoutLossEvent.InputTuple,
    CashoutLossEvent.OutputTuple,
    CashoutLossEvent.OutputObject
  >;
  getEvent(
    key: "CashoutWin"
  ): TypedContractEvent<
    CashoutWinEvent.InputTuple,
    CashoutWinEvent.OutputTuple,
    CashoutWinEvent.OutputObject
  >;
  getEvent(
    key: "EarningsCredited"
  ): TypedContractEvent<
    EarningsCreditedEvent.InputTuple,
    EarningsCreditedEvent.OutputTuple,
    EarningsCreditedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowUpdated"
  ): TypedContractEvent<
    EscrowUpdatedEvent.InputTuple,
    EscrowUpdatedEvent.OutputTuple,
    EscrowUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "HouseFeePaid"
  ): TypedContractEvent<
    HouseFeePaidEvent.InputTuple,
    HouseFeePaidEvent.OutputTuple,
    HouseFeePaidEvent.OutputObject
  >;
  getEvent(
    key: "HouseFeeUpdated"
  ): TypedContractEvent<
    HouseFeeUpdatedEvent.InputTuple,
    HouseFeeUpdatedEvent.OutputTuple,
    HouseFeeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "HouseWalletUpdated"
  ): TypedContractEvent<
    HouseWalletUpdatedEvent.InputTuple,
    HouseWalletUpdatedEvent.OutputTuple,
    HouseWalletUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "MinimumStakeUpdated"
  ): TypedContractEvent<
    MinimumStakeUpdatedEvent.InputTuple,
    MinimumStakeUpdatedEvent.OutputTuple,
    MinimumStakeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PoolSeeded"
  ): TypedContractEvent<
    PoolSeededEvent.InputTuple,
    PoolSeededEvent.OutputTuple,
    PoolSeededEvent.OutputObject
  >;
  getEvent(
    key: "PoolWithdrawn"
  ): TypedContractEvent<
    PoolWithdrawnEvent.InputTuple,
    PoolWithdrawnEvent.OutputTuple,
    PoolWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "Staked"
  ): TypedContractEvent<
    StakedEvent.InputTuple,
    StakedEvent.OutputTuple,
    StakedEvent.OutputObject
  >;
  getEvent(
    key: "Unstaked"
  ): TypedContractEvent<
    UnstakedEvent.InputTuple,
    UnstakedEvent.OutputTuple,
    UnstakedEvent.OutputObject
  >;

  filters: {
    "CashoutLoss(address,uint256)": TypedContractEvent<
      CashoutLossEvent.InputTuple,
      CashoutLossEvent.OutputTuple,
      CashoutLossEvent.OutputObject
    >;
    CashoutLoss: TypedContractEvent<
      CashoutLossEvent.InputTuple,
      CashoutLossEvent.OutputTuple,
      CashoutLossEvent.OutputObject
    >;

    "CashoutWin(address,uint256)": TypedContractEvent<
      CashoutWinEvent.InputTuple,
      CashoutWinEvent.OutputTuple,
      CashoutWinEvent.OutputObject
    >;
    CashoutWin: TypedContractEvent<
      CashoutWinEvent.InputTuple,
      CashoutWinEvent.OutputTuple,
      CashoutWinEvent.OutputObject
    >;

    "EarningsCredited(address,uint256)": TypedContractEvent<
      EarningsCreditedEvent.InputTuple,
      EarningsCreditedEvent.OutputTuple,
      EarningsCreditedEvent.OutputObject
    >;
    EarningsCredited: TypedContractEvent<
      EarningsCreditedEvent.InputTuple,
      EarningsCreditedEvent.OutputTuple,
      EarningsCreditedEvent.OutputObject
    >;

    "EscrowUpdated(address)": TypedContractEvent<
      EscrowUpdatedEvent.InputTuple,
      EscrowUpdatedEvent.OutputTuple,
      EscrowUpdatedEvent.OutputObject
    >;
    EscrowUpdated: TypedContractEvent<
      EscrowUpdatedEvent.InputTuple,
      EscrowUpdatedEvent.OutputTuple,
      EscrowUpdatedEvent.OutputObject
    >;

    "HouseFeePaid(address,uint256)": TypedContractEvent<
      HouseFeePaidEvent.InputTuple,
      HouseFeePaidEvent.OutputTuple,
      HouseFeePaidEvent.OutputObject
    >;
    HouseFeePaid: TypedContractEvent<
      HouseFeePaidEvent.InputTuple,
      HouseFeePaidEvent.OutputTuple,
      HouseFeePaidEvent.OutputObject
    >;

    "HouseFeeUpdated(uint256)": TypedContractEvent<
      HouseFeeUpdatedEvent.InputTuple,
      HouseFeeUpdatedEvent.OutputTuple,
      HouseFeeUpdatedEvent.OutputObject
    >;
    HouseFeeUpdated: TypedContractEvent<
      HouseFeeUpdatedEvent.InputTuple,
      HouseFeeUpdatedEvent.OutputTuple,
      HouseFeeUpdatedEvent.OutputObject
    >;

    "HouseWalletUpdated(address)": TypedContractEvent<
      HouseWalletUpdatedEvent.InputTuple,
      HouseWalletUpdatedEvent.OutputTuple,
      HouseWalletUpdatedEvent.OutputObject
    >;
    HouseWalletUpdated: TypedContractEvent<
      HouseWalletUpdatedEvent.InputTuple,
      HouseWalletUpdatedEvent.OutputTuple,
      HouseWalletUpdatedEvent.OutputObject
    >;

    "MinimumStakeUpdated(uint256)": TypedContractEvent<
      MinimumStakeUpdatedEvent.InputTuple,
      MinimumStakeUpdatedEvent.OutputTuple,
      MinimumStakeUpdatedEvent.OutputObject
    >;
    MinimumStakeUpdated: TypedContractEvent<
      MinimumStakeUpdatedEvent.InputTuple,
      MinimumStakeUpdatedEvent.OutputTuple,
      MinimumStakeUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PoolSeeded(address,uint256)": TypedContractEvent<
      PoolSeededEvent.InputTuple,
      PoolSeededEvent.OutputTuple,
      PoolSeededEvent.OutputObject
    >;
    PoolSeeded: TypedContractEvent<
      PoolSeededEvent.InputTuple,
      PoolSeededEvent.OutputTuple,
      PoolSeededEvent.OutputObject
    >;

    "PoolWithdrawn(address,uint256)": TypedContractEvent<
      PoolWithdrawnEvent.InputTuple,
      PoolWithdrawnEvent.OutputTuple,
      PoolWithdrawnEvent.OutputObject
    >;
    PoolWithdrawn: TypedContractEvent<
      PoolWithdrawnEvent.InputTuple,
      PoolWithdrawnEvent.OutputTuple,
      PoolWithdrawnEvent.OutputObject
    >;

    "Staked(address,uint256)": TypedContractEvent<
      StakedEvent.InputTuple,
      StakedEvent.OutputTuple,
      StakedEvent.OutputObject
    >;
    Staked: TypedContractEvent<
      StakedEvent.InputTuple,
      StakedEvent.OutputTuple,
      StakedEvent.OutputObject
    >;

    "Unstaked(address,uint256,uint256)": TypedContractEvent<
      UnstakedEvent.InputTuple,
      UnstakedEvent.OutputTuple,
      UnstakedEvent.OutputObject
    >;
    Unstaked: TypedContractEvent<
      UnstakedEvent.InputTuple,
      UnstakedEvent.OutputTuple,
      UnstakedEvent.OutputObject
    >;
  };
}
