/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace IJsonApi {
  export type RequestStruct = {
    url: string;
    postprocessJq: string;
    headerKey: string;
    headerValue: string;
  };

  export type RequestStructOutput = [
    url: string,
    postprocessJq: string,
    headerKey: string,
    headerValue: string
  ] & {
    url: string;
    postprocessJq: string;
    headerKey: string;
    headerValue: string;
  };

  export type ResponseStruct = { abiEncodedData: BytesLike };

  export type ResponseStructOutput = [abiEncodedData: string] & {
    abiEncodedData: string;
  };

  export type BodyStruct = {
    attestationType: BytesLike;
    sourceId: BytesLike;
    votingRound: BigNumberish;
    lowestUsedTimestamp: BigNumberish;
    requestBody: IJsonApi.RequestStruct;
    responseBody: IJsonApi.ResponseStruct;
  };

  export type BodyStructOutput = [
    attestationType: string,
    sourceId: string,
    votingRound: bigint,
    lowestUsedTimestamp: bigint,
    requestBody: IJsonApi.RequestStructOutput,
    responseBody: IJsonApi.ResponseStructOutput
  ] & {
    attestationType: string;
    sourceId: string;
    votingRound: bigint;
    lowestUsedTimestamp: bigint;
    requestBody: IJsonApi.RequestStructOutput;
    responseBody: IJsonApi.ResponseStructOutput;
  };

  export type ProofStruct = {
    merkleProof: BytesLike[];
    body: IJsonApi.BodyStruct;
  };

  export type ProofStructOutput = [
    merkleProof: string[],
    body: IJsonApi.BodyStructOutput
  ] & { merkleProof: string[]; body: IJsonApi.BodyStructOutput };
}

export interface FDCVerifierInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "FLARE_CONTRACT_REGISTRY"
      | "JSON_API_ATTESTATION_TYPE"
      | "attestationHashes"
      | "authorisedSubmitters"
      | "deliveryConfirmed"
      | "fdcHub"
      | "fdcVerification"
      | "isDeliveryConfirmed"
      | "manualConfirmDelivery"
      | "owner"
      | "renounceOwnership"
      | "requestDeliveryAttestation"
      | "resolveFdcContracts"
      | "setFdcHub"
      | "setFdcVerification"
      | "setSubmitterAuthorised"
      | "transferOwnership"
      | "verifyDelivery"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DeliveryAttested"
      | "FdcHubSet"
      | "FdcVerificationSet"
      | "OwnershipTransferred"
      | "SubmitterAuthorised"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "FLARE_CONTRACT_REGISTRY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "JSON_API_ATTESTATION_TYPE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "attestationHashes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "authorisedSubmitters",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deliveryConfirmed",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "fdcHub", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "fdcVerification",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isDeliveryConfirmed",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "manualConfirmDelivery",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestDeliveryAttestation",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveFdcContracts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setFdcHub",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setFdcVerification",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setSubmitterAuthorised",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyDelivery",
    values: [BigNumberish, IJsonApi.ProofStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "FLARE_CONTRACT_REGISTRY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "JSON_API_ATTESTATION_TYPE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "attestationHashes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorisedSubmitters",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deliveryConfirmed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fdcHub", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fdcVerification",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isDeliveryConfirmed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "manualConfirmDelivery",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestDeliveryAttestation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveFdcContracts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setFdcHub", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setFdcVerification",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSubmitterAuthorised",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyDelivery",
    data: BytesLike
  ): Result;
}

export namespace DeliveryAttestedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    proofHash: BytesLike,
    submitter: AddressLike
  ];
  export type OutputTuple = [
    jobId: bigint,
    proofHash: string,
    submitter: string
  ];
  export interface OutputObject {
    jobId: bigint;
    proofHash: string;
    submitter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FdcHubSetEvent {
  export type InputTuple = [hub: AddressLike];
  export type OutputTuple = [hub: string];
  export interface OutputObject {
    hub: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FdcVerificationSetEvent {
  export type InputTuple = [verifier: AddressLike];
  export type OutputTuple = [verifier: string];
  export interface OutputObject {
    verifier: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubmitterAuthorisedEvent {
  export type InputTuple = [submitter: AddressLike, authorised: boolean];
  export type OutputTuple = [submitter: string, authorised: boolean];
  export interface OutputObject {
    submitter: string;
    authorised: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FDCVerifier extends BaseContract {
  connect(runner?: ContractRunner | null): FDCVerifier;
  waitForDeployment(): Promise<this>;

  interface: FDCVerifierInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  FLARE_CONTRACT_REGISTRY: TypedContractMethod<[], [string], "view">;

  JSON_API_ATTESTATION_TYPE: TypedContractMethod<[], [string], "view">;

  attestationHashes: TypedContractMethod<
    [arg0: BigNumberish],
    [string],
    "view"
  >;

  authorisedSubmitters: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  deliveryConfirmed: TypedContractMethod<
    [arg0: BigNumberish],
    [boolean],
    "view"
  >;

  fdcHub: TypedContractMethod<[], [string], "view">;

  fdcVerification: TypedContractMethod<[], [string], "view">;

  isDeliveryConfirmed: TypedContractMethod<
    [jobId: BigNumberish],
    [boolean],
    "view"
  >;

  manualConfirmDelivery: TypedContractMethod<
    [jobId: BigNumberish],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  requestDeliveryAttestation: TypedContractMethod<
    [attestationData: BytesLike],
    [string],
    "payable"
  >;

  resolveFdcContracts: TypedContractMethod<[], [void], "nonpayable">;

  setFdcHub: TypedContractMethod<[hub: AddressLike], [void], "nonpayable">;

  setFdcVerification: TypedContractMethod<
    [verifier: AddressLike],
    [void],
    "nonpayable"
  >;

  setSubmitterAuthorised: TypedContractMethod<
    [submitter: AddressLike, authorised: boolean],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  verifyDelivery: TypedContractMethod<
    [jobId: BigNumberish, proof: IJsonApi.ProofStruct],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "FLARE_CONTRACT_REGISTRY"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "JSON_API_ATTESTATION_TYPE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "attestationHashes"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "authorisedSubmitters"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "deliveryConfirmed"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "fdcHub"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "fdcVerification"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "isDeliveryConfirmed"
  ): TypedContractMethod<[jobId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "manualConfirmDelivery"
  ): TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestDeliveryAttestation"
  ): TypedContractMethod<[attestationData: BytesLike], [string], "payable">;
  getFunction(
    nameOrSignature: "resolveFdcContracts"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFdcHub"
  ): TypedContractMethod<[hub: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFdcVerification"
  ): TypedContractMethod<[verifier: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setSubmitterAuthorised"
  ): TypedContractMethod<
    [submitter: AddressLike, authorised: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifyDelivery"
  ): TypedContractMethod<
    [jobId: BigNumberish, proof: IJsonApi.ProofStruct],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "DeliveryAttested"
  ): TypedContractEvent<
    DeliveryAttestedEvent.InputTuple,
    DeliveryAttestedEvent.OutputTuple,
    DeliveryAttestedEvent.OutputObject
  >;
  getEvent(
    key: "FdcHubSet"
  ): TypedContractEvent<
    FdcHubSetEvent.InputTuple,
    FdcHubSetEvent.OutputTuple,
    FdcHubSetEvent.OutputObject
  >;
  getEvent(
    key: "FdcVerificationSet"
  ): TypedContractEvent<
    FdcVerificationSetEvent.InputTuple,
    FdcVerificationSetEvent.OutputTuple,
    FdcVerificationSetEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "SubmitterAuthorised"
  ): TypedContractEvent<
    SubmitterAuthorisedEvent.InputTuple,
    SubmitterAuthorisedEvent.OutputTuple,
    SubmitterAuthorisedEvent.OutputObject
  >;

  filters: {
    "DeliveryAttested(uint256,bytes32,address)": TypedContractEvent<
      DeliveryAttestedEvent.InputTuple,
      DeliveryAttestedEvent.OutputTuple,
      DeliveryAttestedEvent.OutputObject
    >;
    DeliveryAttested: TypedContractEvent<
      DeliveryAttestedEvent.InputTuple,
      DeliveryAttestedEvent.OutputTuple,
      DeliveryAttestedEvent.OutputObject
    >;

    "FdcHubSet(address)": TypedContractEvent<
      FdcHubSetEvent.InputTuple,
      FdcHubSetEvent.OutputTuple,
      FdcHubSetEvent.OutputObject
    >;
    FdcHubSet: TypedContractEvent<
      FdcHubSetEvent.InputTuple,
      FdcHubSetEvent.OutputTuple,
      FdcHubSetEvent.OutputObject
    >;

    "FdcVerificationSet(address)": TypedContractEvent<
      FdcVerificationSetEvent.InputTuple,
      FdcVerificationSetEvent.OutputTuple,
      FdcVerificationSetEvent.OutputObject
    >;
    FdcVerificationSet: TypedContractEvent<
      FdcVerificationSetEvent.InputTuple,
      FdcVerificationSetEvent.OutputTuple,
      FdcVerificationSetEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "SubmitterAuthorised(address,bool)": TypedContractEvent<
      SubmitterAuthorisedEvent.InputTuple,
      SubmitterAuthorisedEvent.OutputTuple,
      SubmitterAuthorisedEvent.OutputObject
    >;
    SubmitterAuthorised: TypedContractEvent<
      SubmitterAuthorisedEvent.InputTuple,
      SubmitterAuthorisedEvent.OutputTuple,
      SubmitterAuthorisedEvent.OutputObject
    >;
  };
}
