/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace FlareOrderBook {
  export type BidStruct = {
    id: BigNumberish;
    jobId: BigNumberish;
    agent: AddressLike;
    priceUsd: BigNumberish;
    priceFlr: BigNumberish;
    estimatedTime: BigNumberish;
    proposal: string;
    createdAt: BigNumberish;
    accepted: boolean;
  };

  export type BidStructOutput = [
    id: bigint,
    jobId: bigint,
    agent: string,
    priceUsd: bigint,
    priceFlr: bigint,
    estimatedTime: bigint,
    proposal: string,
    createdAt: bigint,
    accepted: boolean
  ] & {
    id: bigint;
    jobId: bigint;
    agent: string;
    priceUsd: bigint;
    priceFlr: bigint;
    estimatedTime: bigint;
    proposal: string;
    createdAt: bigint;
    accepted: boolean;
  };

  export type JobStruct = {
    id: BigNumberish;
    poster: AddressLike;
    provider: AddressLike;
    metadataURI: string;
    maxPriceUsd: BigNumberish;
    maxPriceFlr: BigNumberish;
    deadline: BigNumberish;
    status: BigNumberish;
    deliveryProof: BytesLike;
    createdAt: BigNumberish;
    acceptedBidId: BigNumberish;
  };

  export type JobStructOutput = [
    id: bigint,
    poster: string,
    provider: string,
    metadataURI: string,
    maxPriceUsd: bigint,
    maxPriceFlr: bigint,
    deadline: bigint,
    status: bigint,
    deliveryProof: string,
    createdAt: bigint,
    acceptedBidId: bigint
  ] & {
    id: bigint;
    poster: string;
    provider: string;
    metadataURI: string;
    maxPriceUsd: bigint;
    maxPriceFlr: bigint;
    deadline: bigint;
    status: bigint;
    deliveryProof: string;
    createdAt: bigint;
    acceptedBidId: bigint;
  };
}

export interface FlareOrderBookInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptBid"
      | "assignProvider"
      | "bids"
      | "cancelJob"
      | "createJob"
      | "escrow"
      | "ftso"
      | "getBid"
      | "getJob"
      | "getJobBidCount"
      | "getJobBidIds"
      | "getJobIds"
      | "jobBids"
      | "jobIds"
      | "jobs"
      | "markCompleted"
      | "markReleased"
      | "owner"
      | "placeBid"
      | "quoteUsdToFlr"
      | "raiseDispute"
      | "renounceOwnership"
      | "setEscrow"
      | "setFTSO"
      | "totalJobs"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BidAccepted"
      | "BidPlaced"
      | "JobCancelled"
      | "JobCompleted"
      | "JobCreated"
      | "JobDisputed"
      | "JobReleased"
      | "OwnershipTransferred"
      | "ProviderAssigned"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptBid",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "assignProvider",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "bids", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "cancelJob",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createJob",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "escrow", values?: undefined): string;
  encodeFunctionData(functionFragment: "ftso", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getBid",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getJob",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getJobBidCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getJobBidIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getJobIds",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "jobBids",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "jobIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "jobs", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "markCompleted",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "markReleased",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "placeBid",
    values: [BigNumberish, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "quoteUsdToFlr",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "raiseDispute",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setEscrow",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setFTSO",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "totalJobs", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "acceptBid", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "assignProvider",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "bids", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "cancelJob", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "createJob", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "escrow", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ftso", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getBid", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getJob", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getJobBidCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getJobBidIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getJobIds", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "jobBids", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "jobIds", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "jobs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "markCompleted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "markReleased",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "placeBid", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "quoteUsdToFlr",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "raiseDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setEscrow", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setFTSO", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "totalJobs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace BidAcceptedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    bidId: BigNumberish,
    provider: AddressLike
  ];
  export type OutputTuple = [jobId: bigint, bidId: bigint, provider: string];
  export interface OutputObject {
    jobId: bigint;
    bidId: bigint;
    provider: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BidPlacedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    bidId: BigNumberish,
    agent: AddressLike,
    priceUsd: BigNumberish,
    priceFlr: BigNumberish
  ];
  export type OutputTuple = [
    jobId: bigint,
    bidId: bigint,
    agent: string,
    priceUsd: bigint,
    priceFlr: bigint
  ];
  export interface OutputObject {
    jobId: bigint;
    bidId: bigint;
    agent: string;
    priceUsd: bigint;
    priceFlr: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobCancelledEvent {
  export type InputTuple = [jobId: BigNumberish];
  export type OutputTuple = [jobId: bigint];
  export interface OutputObject {
    jobId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobCompletedEvent {
  export type InputTuple = [jobId: BigNumberish, deliveryProof: BytesLike];
  export type OutputTuple = [jobId: bigint, deliveryProof: string];
  export interface OutputObject {
    jobId: bigint;
    deliveryProof: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobCreatedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    poster: AddressLike,
    maxPriceUsd: BigNumberish,
    maxPriceFlr: BigNumberish
  ];
  export type OutputTuple = [
    jobId: bigint,
    poster: string,
    maxPriceUsd: bigint,
    maxPriceFlr: bigint
  ];
  export interface OutputObject {
    jobId: bigint;
    poster: string;
    maxPriceUsd: bigint;
    maxPriceFlr: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobDisputedEvent {
  export type InputTuple = [jobId: BigNumberish, disputedBy: AddressLike];
  export type OutputTuple = [jobId: bigint, disputedBy: string];
  export interface OutputObject {
    jobId: bigint;
    disputedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobReleasedEvent {
  export type InputTuple = [jobId: BigNumberish];
  export type OutputTuple = [jobId: bigint];
  export interface OutputObject {
    jobId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProviderAssignedEvent {
  export type InputTuple = [jobId: BigNumberish, provider: AddressLike];
  export type OutputTuple = [jobId: bigint, provider: string];
  export interface OutputObject {
    jobId: bigint;
    provider: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FlareOrderBook extends BaseContract {
  connect(runner?: ContractRunner | null): FlareOrderBook;
  waitForDeployment(): Promise<this>;

  interface: FlareOrderBookInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptBid: TypedContractMethod<
    [jobId: BigNumberish, bidId: BigNumberish],
    [void],
    "nonpayable"
  >;

  assignProvider: TypedContractMethod<
    [jobId: BigNumberish, provider: AddressLike],
    [void],
    "nonpayable"
  >;

  bids: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        boolean
      ] & {
        id: bigint;
        jobId: bigint;
        agent: string;
        priceUsd: bigint;
        priceFlr: bigint;
        estimatedTime: bigint;
        proposal: string;
        createdAt: bigint;
        accepted: boolean;
      }
    ],
    "view"
  >;

  cancelJob: TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;

  createJob: TypedContractMethod<
    [metadataURI: string, maxPriceUsd: BigNumberish, deadline: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  escrow: TypedContractMethod<[], [string], "view">;

  ftso: TypedContractMethod<[], [string], "view">;

  getBid: TypedContractMethod<
    [bidId: BigNumberish],
    [FlareOrderBook.BidStructOutput],
    "view"
  >;

  getJob: TypedContractMethod<
    [jobId: BigNumberish],
    [FlareOrderBook.JobStructOutput],
    "view"
  >;

  getJobBidCount: TypedContractMethod<[jobId: BigNumberish], [bigint], "view">;

  getJobBidIds: TypedContractMethod<[jobId: BigNumberish], [bigint[]], "view">;

  getJobIds: TypedContractMethod<
    [offset: BigNumberish, limit: BigNumberish],
    [bigint[]],
    "view"
  >;

  jobBids: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  jobIds: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  jobs: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint
      ] & {
        id: bigint;
        poster: string;
        provider: string;
        metadataURI: string;
        maxPriceUsd: bigint;
        maxPriceFlr: bigint;
        deadline: bigint;
        status: bigint;
        deliveryProof: string;
        createdAt: bigint;
        acceptedBidId: bigint;
      }
    ],
    "view"
  >;

  markCompleted: TypedContractMethod<
    [jobId: BigNumberish, deliveryProof: BytesLike],
    [void],
    "nonpayable"
  >;

  markReleased: TypedContractMethod<
    [jobId: BigNumberish],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  placeBid: TypedContractMethod<
    [
      jobId: BigNumberish,
      priceUsd: BigNumberish,
      estimatedTime: BigNumberish,
      proposal: string
    ],
    [bigint],
    "nonpayable"
  >;

  quoteUsdToFlr: TypedContractMethod<
    [usdAmount: BigNumberish],
    [bigint],
    "view"
  >;

  raiseDispute: TypedContractMethod<
    [jobId: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setEscrow: TypedContractMethod<[escrow_: AddressLike], [void], "nonpayable">;

  setFTSO: TypedContractMethod<
    [ftsoConsumer: AddressLike],
    [void],
    "nonpayable"
  >;

  totalJobs: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptBid"
  ): TypedContractMethod<
    [jobId: BigNumberish, bidId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "assignProvider"
  ): TypedContractMethod<
    [jobId: BigNumberish, provider: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "bids"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        boolean
      ] & {
        id: bigint;
        jobId: bigint;
        agent: string;
        priceUsd: bigint;
        priceFlr: bigint;
        estimatedTime: bigint;
        proposal: string;
        createdAt: bigint;
        accepted: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "cancelJob"
  ): TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createJob"
  ): TypedContractMethod<
    [metadataURI: string, maxPriceUsd: BigNumberish, deadline: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "escrow"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ftso"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getBid"
  ): TypedContractMethod<
    [bidId: BigNumberish],
    [FlareOrderBook.BidStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getJob"
  ): TypedContractMethod<
    [jobId: BigNumberish],
    [FlareOrderBook.JobStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getJobBidCount"
  ): TypedContractMethod<[jobId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getJobBidIds"
  ): TypedContractMethod<[jobId: BigNumberish], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getJobIds"
  ): TypedContractMethod<
    [offset: BigNumberish, limit: BigNumberish],
    [bigint[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "jobBids"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "jobIds"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "jobs"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint
      ] & {
        id: bigint;
        poster: string;
        provider: string;
        metadataURI: string;
        maxPriceUsd: bigint;
        maxPriceFlr: bigint;
        deadline: bigint;
        status: bigint;
        deliveryProof: string;
        createdAt: bigint;
        acceptedBidId: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "markCompleted"
  ): TypedContractMethod<
    [jobId: BigNumberish, deliveryProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "markReleased"
  ): TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "placeBid"
  ): TypedContractMethod<
    [
      jobId: BigNumberish,
      priceUsd: BigNumberish,
      estimatedTime: BigNumberish,
      proposal: string
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "quoteUsdToFlr"
  ): TypedContractMethod<[usdAmount: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "raiseDispute"
  ): TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setEscrow"
  ): TypedContractMethod<[escrow_: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFTSO"
  ): TypedContractMethod<[ftsoConsumer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalJobs"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "BidAccepted"
  ): TypedContractEvent<
    BidAcceptedEvent.InputTuple,
    BidAcceptedEvent.OutputTuple,
    BidAcceptedEvent.OutputObject
  >;
  getEvent(
    key: "BidPlaced"
  ): TypedContractEvent<
    BidPlacedEvent.InputTuple,
    BidPlacedEvent.OutputTuple,
    BidPlacedEvent.OutputObject
  >;
  getEvent(
    key: "JobCancelled"
  ): TypedContractEvent<
    JobCancelledEvent.InputTuple,
    JobCancelledEvent.OutputTuple,
    JobCancelledEvent.OutputObject
  >;
  getEvent(
    key: "JobCompleted"
  ): TypedContractEvent<
    JobCompletedEvent.InputTuple,
    JobCompletedEvent.OutputTuple,
    JobCompletedEvent.OutputObject
  >;
  getEvent(
    key: "JobCreated"
  ): TypedContractEvent<
    JobCreatedEvent.InputTuple,
    JobCreatedEvent.OutputTuple,
    JobCreatedEvent.OutputObject
  >;
  getEvent(
    key: "JobDisputed"
  ): TypedContractEvent<
    JobDisputedEvent.InputTuple,
    JobDisputedEvent.OutputTuple,
    JobDisputedEvent.OutputObject
  >;
  getEvent(
    key: "JobReleased"
  ): TypedContractEvent<
    JobReleasedEvent.InputTuple,
    JobReleasedEvent.OutputTuple,
    JobReleasedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ProviderAssigned"
  ): TypedContractEvent<
    ProviderAssignedEvent.InputTuple,
    ProviderAssignedEvent.OutputTuple,
    ProviderAssignedEvent.OutputObject
  >;

  filters: {
    "BidAccepted(uint256,uint256,address)": TypedContractEvent<
      BidAcceptedEvent.InputTuple,
      BidAcceptedEvent.OutputTuple,
      BidAcceptedEvent.OutputObject
    >;
    BidAccepted: TypedContractEvent<
      BidAcceptedEvent.InputTuple,
      BidAcceptedEvent.OutputTuple,
      BidAcceptedEvent.OutputObject
    >;

    "BidPlaced(uint256,uint256,address,uint256,uint256)": TypedContractEvent<
      BidPlacedEvent.InputTuple,
      BidPlacedEvent.OutputTuple,
      BidPlacedEvent.OutputObject
    >;
    BidPlaced: TypedContractEvent<
      BidPlacedEvent.InputTuple,
      BidPlacedEvent.OutputTuple,
      BidPlacedEvent.OutputObject
    >;

    "JobCancelled(uint256)": TypedContractEvent<
      JobCancelledEvent.InputTuple,
      JobCancelledEvent.OutputTuple,
      JobCancelledEvent.OutputObject
    >;
    JobCancelled: TypedContractEvent<
      JobCancelledEvent.InputTuple,
      JobCancelledEvent.OutputTuple,
      JobCancelledEvent.OutputObject
    >;

    "JobCompleted(uint256,bytes32)": TypedContractEvent<
      JobCompletedEvent.InputTuple,
      JobCompletedEvent.OutputTuple,
      JobCompletedEvent.OutputObject
    >;
    JobCompleted: TypedContractEvent<
      JobCompletedEvent.InputTuple,
      JobCompletedEvent.OutputTuple,
      JobCompletedEvent.OutputObject
    >;

    "JobCreated(uint256,address,uint256,uint256)": TypedContractEvent<
      JobCreatedEvent.InputTuple,
      JobCreatedEvent.OutputTuple,
      JobCreatedEvent.OutputObject
    >;
    JobCreated: TypedContractEvent<
      JobCreatedEvent.InputTuple,
      JobCreatedEvent.OutputTuple,
      JobCreatedEvent.OutputObject
    >;

    "JobDisputed(uint256,address)": TypedContractEvent<
      JobDisputedEvent.InputTuple,
      JobDisputedEvent.OutputTuple,
      JobDisputedEvent.OutputObject
    >;
    JobDisputed: TypedContractEvent<
      JobDisputedEvent.InputTuple,
      JobDisputedEvent.OutputTuple,
      JobDisputedEvent.OutputObject
    >;

    "JobReleased(uint256)": TypedContractEvent<
      JobReleasedEvent.InputTuple,
      JobReleasedEvent.OutputTuple,
      JobReleasedEvent.OutputObject
    >;
    JobReleased: TypedContractEvent<
      JobReleasedEvent.InputTuple,
      JobReleasedEvent.OutputTuple,
      JobReleasedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ProviderAssigned(uint256,address)": TypedContractEvent<
      ProviderAssignedEvent.InputTuple,
      ProviderAssignedEvent.OutputTuple,
      ProviderAssignedEvent.OutputObject
    >;
    ProviderAssigned: TypedContractEvent<
      ProviderAssignedEvent.InputTuple,
      ProviderAssignedEvent.OutputTuple,
      ProviderAssignedEvent.OutputObject
    >;
  };
}
