/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface FTSOPriceConsumerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "FLARE_CONTRACT_REGISTRY"
      | "FLR_USD_FEED_INDEX"
      | "fastUpdater"
      | "flrToUsd"
      | "getFlrUsdPrice"
      | "maxStaleness"
      | "owner"
      | "renounceOwnership"
      | "resolveFastUpdater"
      | "setFastUpdater"
      | "setMaxStaleness"
      | "transferOwnership"
      | "usdToFlr"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FastUpdaterSet"
      | "MaxStalenessUpdated"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "FLARE_CONTRACT_REGISTRY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "FLR_USD_FEED_INDEX",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fastUpdater",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "flrToUsd",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getFlrUsdPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxStaleness",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resolveFastUpdater",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setFastUpdater",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxStaleness",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "usdToFlr",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "FLARE_CONTRACT_REGISTRY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FLR_USD_FEED_INDEX",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fastUpdater",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "flrToUsd", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getFlrUsdPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxStaleness",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveFastUpdater",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFastUpdater",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxStaleness",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdToFlr", data: BytesLike): Result;
}

export namespace FastUpdaterSetEvent {
  export type InputTuple = [updater: AddressLike];
  export type OutputTuple = [updater: string];
  export interface OutputObject {
    updater: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MaxStalenessUpdatedEvent {
  export type InputTuple = [newStaleness: BigNumberish];
  export type OutputTuple = [newStaleness: bigint];
  export interface OutputObject {
    newStaleness: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FTSOPriceConsumer extends BaseContract {
  connect(runner?: ContractRunner | null): FTSOPriceConsumer;
  waitForDeployment(): Promise<this>;

  interface: FTSOPriceConsumerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  FLARE_CONTRACT_REGISTRY: TypedContractMethod<[], [string], "view">;

  FLR_USD_FEED_INDEX: TypedContractMethod<[], [bigint], "view">;

  fastUpdater: TypedContractMethod<[], [string], "view">;

  flrToUsd: TypedContractMethod<[flrAmount: BigNumberish], [bigint], "view">;

  getFlrUsdPrice: TypedContractMethod<
    [],
    [[bigint, bigint] & { priceWei: bigint; timestamp: bigint }],
    "view"
  >;

  maxStaleness: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  resolveFastUpdater: TypedContractMethod<[], [void], "nonpayable">;

  setFastUpdater: TypedContractMethod<
    [updater: AddressLike],
    [void],
    "nonpayable"
  >;

  setMaxStaleness: TypedContractMethod<
    [seconds_: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  usdToFlr: TypedContractMethod<[usdAmount: BigNumberish], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "FLARE_CONTRACT_REGISTRY"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "FLR_USD_FEED_INDEX"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "fastUpdater"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "flrToUsd"
  ): TypedContractMethod<[flrAmount: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getFlrUsdPrice"
  ): TypedContractMethod<
    [],
    [[bigint, bigint] & { priceWei: bigint; timestamp: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "maxStaleness"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resolveFastUpdater"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFastUpdater"
  ): TypedContractMethod<[updater: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMaxStaleness"
  ): TypedContractMethod<[seconds_: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usdToFlr"
  ): TypedContractMethod<[usdAmount: BigNumberish], [bigint], "view">;

  getEvent(
    key: "FastUpdaterSet"
  ): TypedContractEvent<
    FastUpdaterSetEvent.InputTuple,
    FastUpdaterSetEvent.OutputTuple,
    FastUpdaterSetEvent.OutputObject
  >;
  getEvent(
    key: "MaxStalenessUpdated"
  ): TypedContractEvent<
    MaxStalenessUpdatedEvent.InputTuple,
    MaxStalenessUpdatedEvent.OutputTuple,
    MaxStalenessUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "FastUpdaterSet(address)": TypedContractEvent<
      FastUpdaterSetEvent.InputTuple,
      FastUpdaterSetEvent.OutputTuple,
      FastUpdaterSetEvent.OutputObject
    >;
    FastUpdaterSet: TypedContractEvent<
      FastUpdaterSetEvent.InputTuple,
      FastUpdaterSetEvent.OutputTuple,
      FastUpdaterSetEvent.OutputObject
    >;

    "MaxStalenessUpdated(uint256)": TypedContractEvent<
      MaxStalenessUpdatedEvent.InputTuple,
      MaxStalenessUpdatedEvent.OutputTuple,
      MaxStalenessUpdatedEvent.OutputObject
    >;
    MaxStalenessUpdated: TypedContractEvent<
      MaxStalenessUpdatedEvent.InputTuple,
      MaxStalenessUpdatedEvent.OutputTuple,
      MaxStalenessUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
