/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace JobTypes {
  export type BidMetadataStruct = {
    id: BigNumberish;
    jobId: BigNumberish;
    bidder: AddressLike;
    price: BigNumberish;
    deliveryTime: BigNumberish;
    reputation: BigNumberish;
    metadataURI: string;
    accepted: boolean;
    createdAt: BigNumberish;
  };

  export type BidMetadataStructOutput = [
    id: bigint,
    jobId: bigint,
    bidder: string,
    price: bigint,
    deliveryTime: bigint,
    reputation: bigint,
    metadataURI: string,
    accepted: boolean,
    createdAt: bigint
  ] & {
    id: bigint;
    jobId: bigint;
    bidder: string;
    price: bigint;
    deliveryTime: bigint;
    reputation: bigint;
    metadataURI: string;
    accepted: boolean;
    createdAt: bigint;
  };

  export type JobMetadataStruct = {
    id: BigNumberish;
    poster: AddressLike;
    description: string;
    metadataURI: string;
    tags: string[];
    deadline: BigNumberish;
    createdAt: BigNumberish;
  };

  export type JobMetadataStructOutput = [
    id: bigint,
    poster: string,
    description: string,
    metadataURI: string,
    tags: string[],
    deadline: bigint,
    createdAt: bigint
  ] & {
    id: bigint;
    poster: string;
    description: string;
    metadataURI: string;
    tags: string[];
    deadline: bigint;
    createdAt: bigint;
  };

  export type DeliveryReceiptStruct = {
    jobId: BigNumberish;
    proofHash: BytesLike;
    deliveredAt: BigNumberish;
  };

  export type DeliveryReceiptStructOutput = [
    jobId: bigint,
    proofHash: string,
    deliveredAt: bigint
  ] & { jobId: bigint; proofHash: string; deliveredAt: bigint };
}

export declare namespace JobRegistry {
  export type StoredJobStruct = {
    metadata: JobTypes.JobMetadataStruct;
    status: BigNumberish;
    deliveryProof: BytesLike;
    deliveredAt: BigNumberish;
  };

  export type StoredJobStructOutput = [
    metadata: JobTypes.JobMetadataStructOutput,
    status: bigint,
    deliveryProof: string,
    deliveredAt: bigint
  ] & {
    metadata: JobTypes.JobMetadataStructOutput;
    status: bigint;
    deliveryProof: string;
    deliveredAt: bigint;
  };
}

export interface JobRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getBids"
      | "getJob"
      | "indexBid"
      | "indexDelivery"
      | "orderBook"
      | "owner"
      | "renounceOwnership"
      | "setOrderBook"
      | "transferOwnership"
      | "updateJobStatus"
      | "upsertJob"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BidIndexed"
      | "DeliveryIndexed"
      | "JobIndexed"
      | "OrderBookUpdated"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getBids",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getJob",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "indexBid",
    values: [JobTypes.BidMetadataStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "indexDelivery",
    values: [JobTypes.DeliveryReceiptStruct]
  ): string;
  encodeFunctionData(functionFragment: "orderBook", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setOrderBook",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateJobStatus",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "upsertJob",
    values: [JobTypes.JobMetadataStruct, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "getBids", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getJob", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "indexBid", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "indexDelivery",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "orderBook", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setOrderBook",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateJobStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "upsertJob", data: BytesLike): Result;
}

export namespace BidIndexedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    bidId: BigNumberish,
    bidder: AddressLike
  ];
  export type OutputTuple = [jobId: bigint, bidId: bigint, bidder: string];
  export interface OutputObject {
    jobId: bigint;
    bidId: bigint;
    bidder: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DeliveryIndexedEvent {
  export type InputTuple = [jobId: BigNumberish, proofHash: BytesLike];
  export type OutputTuple = [jobId: bigint, proofHash: string];
  export interface OutputObject {
    jobId: bigint;
    proofHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobIndexedEvent {
  export type InputTuple = [jobId: BigNumberish, poster: AddressLike];
  export type OutputTuple = [jobId: bigint, poster: string];
  export interface OutputObject {
    jobId: bigint;
    poster: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderBookUpdatedEvent {
  export type InputTuple = [orderBook: AddressLike];
  export type OutputTuple = [orderBook: string];
  export interface OutputObject {
    orderBook: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface JobRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): JobRegistry;
  waitForDeployment(): Promise<this>;

  interface: JobRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getBids: TypedContractMethod<
    [jobId: BigNumberish],
    [JobTypes.BidMetadataStructOutput[]],
    "view"
  >;

  getJob: TypedContractMethod<
    [jobId: BigNumberish],
    [
      [
        JobRegistry.StoredJobStructOutput,
        JobTypes.BidMetadataStructOutput[]
      ] & {
        job: JobRegistry.StoredJobStructOutput;
        bids: JobTypes.BidMetadataStructOutput[];
      }
    ],
    "view"
  >;

  indexBid: TypedContractMethod<
    [bid: JobTypes.BidMetadataStruct],
    [void],
    "nonpayable"
  >;

  indexDelivery: TypedContractMethod<
    [receipt: JobTypes.DeliveryReceiptStruct],
    [void],
    "nonpayable"
  >;

  orderBook: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setOrderBook: TypedContractMethod<
    [newOrderBook: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateJobStatus: TypedContractMethod<
    [jobId: BigNumberish, status: BigNumberish],
    [void],
    "nonpayable"
  >;

  upsertJob: TypedContractMethod<
    [job: JobTypes.JobMetadataStruct, status: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getBids"
  ): TypedContractMethod<
    [jobId: BigNumberish],
    [JobTypes.BidMetadataStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getJob"
  ): TypedContractMethod<
    [jobId: BigNumberish],
    [
      [
        JobRegistry.StoredJobStructOutput,
        JobTypes.BidMetadataStructOutput[]
      ] & {
        job: JobRegistry.StoredJobStructOutput;
        bids: JobTypes.BidMetadataStructOutput[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "indexBid"
  ): TypedContractMethod<
    [bid: JobTypes.BidMetadataStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "indexDelivery"
  ): TypedContractMethod<
    [receipt: JobTypes.DeliveryReceiptStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "orderBook"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setOrderBook"
  ): TypedContractMethod<[newOrderBook: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateJobStatus"
  ): TypedContractMethod<
    [jobId: BigNumberish, status: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "upsertJob"
  ): TypedContractMethod<
    [job: JobTypes.JobMetadataStruct, status: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "BidIndexed"
  ): TypedContractEvent<
    BidIndexedEvent.InputTuple,
    BidIndexedEvent.OutputTuple,
    BidIndexedEvent.OutputObject
  >;
  getEvent(
    key: "DeliveryIndexed"
  ): TypedContractEvent<
    DeliveryIndexedEvent.InputTuple,
    DeliveryIndexedEvent.OutputTuple,
    DeliveryIndexedEvent.OutputObject
  >;
  getEvent(
    key: "JobIndexed"
  ): TypedContractEvent<
    JobIndexedEvent.InputTuple,
    JobIndexedEvent.OutputTuple,
    JobIndexedEvent.OutputObject
  >;
  getEvent(
    key: "OrderBookUpdated"
  ): TypedContractEvent<
    OrderBookUpdatedEvent.InputTuple,
    OrderBookUpdatedEvent.OutputTuple,
    OrderBookUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "BidIndexed(uint256,uint256,address)": TypedContractEvent<
      BidIndexedEvent.InputTuple,
      BidIndexedEvent.OutputTuple,
      BidIndexedEvent.OutputObject
    >;
    BidIndexed: TypedContractEvent<
      BidIndexedEvent.InputTuple,
      BidIndexedEvent.OutputTuple,
      BidIndexedEvent.OutputObject
    >;

    "DeliveryIndexed(uint256,bytes32)": TypedContractEvent<
      DeliveryIndexedEvent.InputTuple,
      DeliveryIndexedEvent.OutputTuple,
      DeliveryIndexedEvent.OutputObject
    >;
    DeliveryIndexed: TypedContractEvent<
      DeliveryIndexedEvent.InputTuple,
      DeliveryIndexedEvent.OutputTuple,
      DeliveryIndexedEvent.OutputObject
    >;

    "JobIndexed(uint256,address)": TypedContractEvent<
      JobIndexedEvent.InputTuple,
      JobIndexedEvent.OutputTuple,
      JobIndexedEvent.OutputObject
    >;
    JobIndexed: TypedContractEvent<
      JobIndexedEvent.InputTuple,
      JobIndexedEvent.OutputTuple,
      JobIndexedEvent.OutputObject
    >;

    "OrderBookUpdated(address)": TypedContractEvent<
      OrderBookUpdatedEvent.InputTuple,
      OrderBookUpdatedEvent.OutputTuple,
      OrderBookUpdatedEvent.OutputObject
    >;
    OrderBookUpdated: TypedContractEvent<
      OrderBookUpdatedEvent.InputTuple,
      OrderBookUpdatedEvent.OutputTuple,
      OrderBookUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
