/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IFDCVerifier,
  IFDCVerifierInterface,
} from "../../../contracts/FlareEscrow.sol/IFDCVerifier";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "jobId",
        type: "uint256",
      },
    ],
    name: "isDeliveryConfirmed",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IFDCVerifier__factory {
  static readonly abi = _abi;
  static createInterface(): IFDCVerifierInterface {
    return new Interface(_abi) as IFDCVerifierInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IFDCVerifier {
    return new Contract(address, _abi, runner) as unknown as IFDCVerifier;
  }
}
