/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IFlareOrderBook,
  IFlareOrderBookInterface,
} from "../../../contracts/FlareEscrow.sol/IFlareOrderBook";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "jobId",
        type: "uint256",
      },
    ],
    name: "markReleased",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IFlareOrderBook__factory {
  static readonly abi = _abi;
  static createInterface(): IFlareOrderBookInterface {
    return new Interface(_abi) as IFlareOrderBookInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IFlareOrderBook {
    return new Contract(address, _abi, runner) as unknown as IFlareOrderBook;
  }
}
