/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace ReputationToken {
  export type AgentStatsStruct = {
    jobsCompleted: BigNumberish;
    jobsFailed: BigNumberish;
    totalEarned: BigNumberish;
    lastUpdated: BigNumberish;
  };

  export type AgentStatsStructOutput = [
    jobsCompleted: bigint,
    jobsFailed: bigint,
    totalEarned: bigint,
    lastUpdated: bigint
  ] & {
    jobsCompleted: bigint;
    jobsFailed: bigint;
    totalEarned: bigint;
    lastUpdated: bigint;
  };
}

export interface ReputationTokenInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "agentRegistry"
      | "escrow"
      | "owner"
      | "recordFailure"
      | "recordSuccess"
      | "renounceOwnership"
      | "scoreOf"
      | "setAgentRegistry"
      | "setEscrow"
      | "statsOf"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentRegistryUpdated"
      | "EscrowUpdated"
      | "OwnershipTransferred"
      | "ReputationUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "agentRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "escrow", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "recordFailure",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recordSuccess",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "scoreOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAgentRegistry",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setEscrow",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "statsOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "agentRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "escrow", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordFailure",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordSuccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "scoreOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAgentRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setEscrow", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "statsOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace AgentRegistryUpdatedEvent {
  export type InputTuple = [registry: AddressLike];
  export type OutputTuple = [registry: string];
  export interface OutputObject {
    registry: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowUpdatedEvent {
  export type InputTuple = [escrow: AddressLike];
  export type OutputTuple = [escrow: string];
  export interface OutputObject {
    escrow: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReputationUpdatedEvent {
  export type InputTuple = [
    agent: AddressLike,
    score: BigNumberish,
    stats: ReputationToken.AgentStatsStruct
  ];
  export type OutputTuple = [
    agent: string,
    score: bigint,
    stats: ReputationToken.AgentStatsStructOutput
  ];
  export interface OutputObject {
    agent: string;
    score: bigint;
    stats: ReputationToken.AgentStatsStructOutput;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ReputationToken extends BaseContract {
  connect(runner?: ContractRunner | null): ReputationToken;
  waitForDeployment(): Promise<this>;

  interface: ReputationTokenInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  agentRegistry: TypedContractMethod<[], [string], "view">;

  escrow: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  recordFailure: TypedContractMethod<
    [agent: AddressLike],
    [void],
    "nonpayable"
  >;

  recordSuccess: TypedContractMethod<
    [agent: AddressLike, payoutAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  scoreOf: TypedContractMethod<[agent: AddressLike], [bigint], "view">;

  setAgentRegistry: TypedContractMethod<
    [registry: AddressLike],
    [void],
    "nonpayable"
  >;

  setEscrow: TypedContractMethod<
    [newEscrow: AddressLike],
    [void],
    "nonpayable"
  >;

  statsOf: TypedContractMethod<
    [agent: AddressLike],
    [ReputationToken.AgentStatsStructOutput],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "agentRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "escrow"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "recordFailure"
  ): TypedContractMethod<[agent: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "recordSuccess"
  ): TypedContractMethod<
    [agent: AddressLike, payoutAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "scoreOf"
  ): TypedContractMethod<[agent: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "setAgentRegistry"
  ): TypedContractMethod<[registry: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setEscrow"
  ): TypedContractMethod<[newEscrow: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "statsOf"
  ): TypedContractMethod<
    [agent: AddressLike],
    [ReputationToken.AgentStatsStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AgentRegistryUpdated"
  ): TypedContractEvent<
    AgentRegistryUpdatedEvent.InputTuple,
    AgentRegistryUpdatedEvent.OutputTuple,
    AgentRegistryUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowUpdated"
  ): TypedContractEvent<
    EscrowUpdatedEvent.InputTuple,
    EscrowUpdatedEvent.OutputTuple,
    EscrowUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ReputationUpdated"
  ): TypedContractEvent<
    ReputationUpdatedEvent.InputTuple,
    ReputationUpdatedEvent.OutputTuple,
    ReputationUpdatedEvent.OutputObject
  >;

  filters: {
    "AgentRegistryUpdated(address)": TypedContractEvent<
      AgentRegistryUpdatedEvent.InputTuple,
      AgentRegistryUpdatedEvent.OutputTuple,
      AgentRegistryUpdatedEvent.OutputObject
    >;
    AgentRegistryUpdated: TypedContractEvent<
      AgentRegistryUpdatedEvent.InputTuple,
      AgentRegistryUpdatedEvent.OutputTuple,
      AgentRegistryUpdatedEvent.OutputObject
    >;

    "EscrowUpdated(address)": TypedContractEvent<
      EscrowUpdatedEvent.InputTuple,
      EscrowUpdatedEvent.OutputTuple,
      EscrowUpdatedEvent.OutputObject
    >;
    EscrowUpdated: TypedContractEvent<
      EscrowUpdatedEvent.InputTuple,
      EscrowUpdatedEvent.OutputTuple,
      EscrowUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ReputationUpdated(address,uint256,tuple)": TypedContractEvent<
      ReputationUpdatedEvent.InputTuple,
      ReputationUpdatedEvent.OutputTuple,
      ReputationUpdatedEvent.OutputObject
    >;
    ReputationUpdated: TypedContractEvent<
      ReputationUpdatedEvent.InputTuple,
      ReputationUpdatedEvent.OutputTuple,
      ReputationUpdatedEvent.OutputObject
    >;
  };
}
