/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace FlareEscrow {
  export type DepositStruct = {
    poster: AddressLike;
    provider: AddressLike;
    amount: BigNumberish;
    usdValue: BigNumberish;
    paymentType: BigNumberish;
    token: AddressLike;
    funded: boolean;
    released: boolean;
    refunded: boolean;
  };

  export type DepositStructOutput = [
    poster: string,
    provider: string,
    amount: bigint,
    usdValue: bigint,
    paymentType: bigint,
    token: string,
    funded: boolean,
    released: boolean,
    refunded: boolean
  ] & {
    poster: string;
    provider: string;
    amount: bigint;
    usdValue: bigint;
    paymentType: bigint;
    token: string;
    funded: boolean;
    released: boolean;
    refunded: boolean;
  };
}

export interface FlareEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "allowedStablecoins"
      | "deposits"
      | "fdcVerifier"
      | "feeCollector"
      | "ftso"
      | "fundJob"
      | "fundJobWithStablecoin"
      | "getDeposit"
      | "isStablecoinAllowed"
      | "orderBook"
      | "owner"
      | "platformFeeBps"
      | "refund"
      | "releaseToProvider"
      | "renounceOwnership"
      | "setAllowedStablecoin"
      | "setFTSO"
      | "setFdcVerifier"
      | "setFeeCollector"
      | "setOrderBook"
      | "setSlippageBps"
      | "slippageBps"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EscrowFunded"
      | "OwnershipTransferred"
      | "PaymentRefunded"
      | "PaymentReleased"
      | "StablecoinUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "allowedStablecoins",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deposits",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fdcVerifier",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "feeCollector",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "ftso", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "fundJob",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fundJobWithStablecoin",
    values: [BigNumberish, AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDeposit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isStablecoinAllowed",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "orderBook", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "platformFeeBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "refund",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "releaseToProvider",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAllowedStablecoin",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setFTSO",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setFdcVerifier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeCollector",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setOrderBook",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setSlippageBps",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "slippageBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "allowedStablecoins",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposits", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fdcVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "feeCollector",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ftso", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fundJob", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fundJobWithStablecoin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getDeposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isStablecoinAllowed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "orderBook", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "refund", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "releaseToProvider",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAllowedStablecoin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setFTSO", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setFdcVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFeeCollector",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setOrderBook",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSlippageBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "slippageBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace EscrowFundedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    poster: AddressLike,
    provider: AddressLike,
    amount: BigNumberish,
    amountUsd: BigNumberish,
    paymentType: BigNumberish,
    token: AddressLike
  ];
  export type OutputTuple = [
    jobId: bigint,
    poster: string,
    provider: string,
    amount: bigint,
    amountUsd: bigint,
    paymentType: bigint,
    token: string
  ];
  export interface OutputObject {
    jobId: bigint;
    poster: string;
    provider: string;
    amount: bigint;
    amountUsd: bigint;
    paymentType: bigint;
    token: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentRefundedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    poster: AddressLike,
    amount: BigNumberish,
    paymentType: BigNumberish
  ];
  export type OutputTuple = [
    jobId: bigint,
    poster: string,
    amount: bigint,
    paymentType: bigint
  ];
  export interface OutputObject {
    jobId: bigint;
    poster: string;
    amount: bigint;
    paymentType: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentReleasedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    provider: AddressLike,
    payout: BigNumberish,
    fee: BigNumberish,
    paymentType: BigNumberish
  ];
  export type OutputTuple = [
    jobId: bigint,
    provider: string,
    payout: bigint,
    fee: bigint,
    paymentType: bigint
  ];
  export interface OutputObject {
    jobId: bigint;
    provider: string;
    payout: bigint;
    fee: bigint;
    paymentType: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StablecoinUpdatedEvent {
  export type InputTuple = [token: AddressLike, allowed: boolean];
  export type OutputTuple = [token: string, allowed: boolean];
  export interface OutputObject {
    token: string;
    allowed: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FlareEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): FlareEscrow;
  waitForDeployment(): Promise<this>;

  interface: FlareEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  allowedStablecoins: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  deposits: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        boolean,
        boolean,
        boolean
      ] & {
        poster: string;
        provider: string;
        amount: bigint;
        usdValue: bigint;
        paymentType: bigint;
        token: string;
        funded: boolean;
        released: boolean;
        refunded: boolean;
      }
    ],
    "view"
  >;

  fdcVerifier: TypedContractMethod<[], [string], "view">;

  feeCollector: TypedContractMethod<[], [string], "view">;

  ftso: TypedContractMethod<[], [string], "view">;

  fundJob: TypedContractMethod<
    [jobId: BigNumberish, provider: AddressLike, usdBudget: BigNumberish],
    [void],
    "payable"
  >;

  fundJobWithStablecoin: TypedContractMethod<
    [
      jobId: BigNumberish,
      provider: AddressLike,
      token: AddressLike,
      amount: BigNumberish,
      usdBudget: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getDeposit: TypedContractMethod<
    [jobId: BigNumberish],
    [FlareEscrow.DepositStructOutput],
    "view"
  >;

  isStablecoinAllowed: TypedContractMethod<
    [token: AddressLike],
    [boolean],
    "view"
  >;

  orderBook: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  platformFeeBps: TypedContractMethod<[], [bigint], "view">;

  refund: TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;

  releaseToProvider: TypedContractMethod<
    [jobId: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setAllowedStablecoin: TypedContractMethod<
    [token: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;

  setFTSO: TypedContractMethod<
    [ftsoConsumer: AddressLike],
    [void],
    "nonpayable"
  >;

  setFdcVerifier: TypedContractMethod<
    [verifier: AddressLike],
    [void],
    "nonpayable"
  >;

  setFeeCollector: TypedContractMethod<
    [collector: AddressLike, feeBps: BigNumberish],
    [void],
    "nonpayable"
  >;

  setOrderBook: TypedContractMethod<
    [orderBook_: AddressLike],
    [void],
    "nonpayable"
  >;

  setSlippageBps: TypedContractMethod<
    [bps: BigNumberish],
    [void],
    "nonpayable"
  >;

  slippageBps: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "allowedStablecoins"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "deposits"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        boolean,
        boolean,
        boolean
      ] & {
        poster: string;
        provider: string;
        amount: bigint;
        usdValue: bigint;
        paymentType: bigint;
        token: string;
        funded: boolean;
        released: boolean;
        refunded: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "fdcVerifier"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "feeCollector"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ftso"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "fundJob"
  ): TypedContractMethod<
    [jobId: BigNumberish, provider: AddressLike, usdBudget: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "fundJobWithStablecoin"
  ): TypedContractMethod<
    [
      jobId: BigNumberish,
      provider: AddressLike,
      token: AddressLike,
      amount: BigNumberish,
      usdBudget: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getDeposit"
  ): TypedContractMethod<
    [jobId: BigNumberish],
    [FlareEscrow.DepositStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "isStablecoinAllowed"
  ): TypedContractMethod<[token: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "orderBook"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "platformFeeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "refund"
  ): TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "releaseToProvider"
  ): TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAllowedStablecoin"
  ): TypedContractMethod<
    [token: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setFTSO"
  ): TypedContractMethod<[ftsoConsumer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFdcVerifier"
  ): TypedContractMethod<[verifier: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFeeCollector"
  ): TypedContractMethod<
    [collector: AddressLike, feeBps: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setOrderBook"
  ): TypedContractMethod<[orderBook_: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setSlippageBps"
  ): TypedContractMethod<[bps: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "slippageBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "EscrowFunded"
  ): TypedContractEvent<
    EscrowFundedEvent.InputTuple,
    EscrowFundedEvent.OutputTuple,
    EscrowFundedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PaymentRefunded"
  ): TypedContractEvent<
    PaymentRefundedEvent.InputTuple,
    PaymentRefundedEvent.OutputTuple,
    PaymentRefundedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentReleased"
  ): TypedContractEvent<
    PaymentReleasedEvent.InputTuple,
    PaymentReleasedEvent.OutputTuple,
    PaymentReleasedEvent.OutputObject
  >;
  getEvent(
    key: "StablecoinUpdated"
  ): TypedContractEvent<
    StablecoinUpdatedEvent.InputTuple,
    StablecoinUpdatedEvent.OutputTuple,
    StablecoinUpdatedEvent.OutputObject
  >;

  filters: {
    "EscrowFunded(uint256,address,address,uint256,uint256,uint8,address)": TypedContractEvent<
      EscrowFundedEvent.InputTuple,
      EscrowFundedEvent.OutputTuple,
      EscrowFundedEvent.OutputObject
    >;
    EscrowFunded: TypedContractEvent<
      EscrowFundedEvent.InputTuple,
      EscrowFundedEvent.OutputTuple,
      EscrowFundedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PaymentRefunded(uint256,address,uint256,uint8)": TypedContractEvent<
      PaymentRefundedEvent.InputTuple,
      PaymentRefundedEvent.OutputTuple,
      PaymentRefundedEvent.OutputObject
    >;
    PaymentRefunded: TypedContractEvent<
      PaymentRefundedEvent.InputTuple,
      PaymentRefundedEvent.OutputTuple,
      PaymentRefundedEvent.OutputObject
    >;

    "PaymentReleased(uint256,address,uint256,uint256,uint8)": TypedContractEvent<
      PaymentReleasedEvent.InputTuple,
      PaymentReleasedEvent.OutputTuple,
      PaymentReleasedEvent.OutputObject
    >;
    PaymentReleased: TypedContractEvent<
      PaymentReleasedEvent.InputTuple,
      PaymentReleasedEvent.OutputTuple,
      PaymentReleasedEvent.OutputObject
    >;

    "StablecoinUpdated(address,bool)": TypedContractEvent<
      StablecoinUpdatedEvent.InputTuple,
      StablecoinUpdatedEvent.OutputTuple,
      StablecoinUpdatedEvent.OutputObject
    >;
    StablecoinUpdated: TypedContractEvent<
      StablecoinUpdatedEvent.InputTuple,
      StablecoinUpdatedEvent.OutputTuple,
      StablecoinUpdatedEvent.OutputObject
    >;
  };
}
