/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IFastUpdaterInterface extends Interface {
  getFunction(nameOrSignature: "fetchCurrentFeeds"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "fetchCurrentFeeds",
    values: [BigNumberish[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "fetchCurrentFeeds",
    data: BytesLike
  ): Result;
}

export interface IFastUpdater extends BaseContract {
  connect(runner?: ContractRunner | null): IFastUpdater;
  waitForDeployment(): Promise<this>;

  interface: IFastUpdaterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  fetchCurrentFeeds: TypedContractMethod<
    [_feedIndexes: BigNumberish[]],
    [
      [bigint[], bigint[], bigint] & {
        _feeds: bigint[];
        _decimals: bigint[];
        _timestamp: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "fetchCurrentFeeds"
  ): TypedContractMethod<
    [_feedIndexes: BigNumberish[]],
    [
      [bigint[], bigint[], bigint] & {
        _feeds: bigint[];
        _decimals: bigint[];
        _timestamp: bigint;
      }
    ],
    "view"
  >;

  filters: {};
}
