/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IJsonApi {
  export type RequestStruct = {
    url: string;
    postprocessJq: string;
    headerKey: string;
    headerValue: string;
  };

  export type RequestStructOutput = [
    url: string,
    postprocessJq: string,
    headerKey: string,
    headerValue: string
  ] & {
    url: string;
    postprocessJq: string;
    headerKey: string;
    headerValue: string;
  };

  export type ResponseStruct = { abiEncodedData: BytesLike };

  export type ResponseStructOutput = [abiEncodedData: string] & {
    abiEncodedData: string;
  };

  export type BodyStruct = {
    attestationType: BytesLike;
    sourceId: BytesLike;
    votingRound: BigNumberish;
    lowestUsedTimestamp: BigNumberish;
    requestBody: IJsonApi.RequestStruct;
    responseBody: IJsonApi.ResponseStruct;
  };

  export type BodyStructOutput = [
    attestationType: string,
    sourceId: string,
    votingRound: bigint,
    lowestUsedTimestamp: bigint,
    requestBody: IJsonApi.RequestStructOutput,
    responseBody: IJsonApi.ResponseStructOutput
  ] & {
    attestationType: string;
    sourceId: string;
    votingRound: bigint;
    lowestUsedTimestamp: bigint;
    requestBody: IJsonApi.RequestStructOutput;
    responseBody: IJsonApi.ResponseStructOutput;
  };

  export type ProofStruct = {
    merkleProof: BytesLike[];
    body: IJsonApi.BodyStruct;
  };

  export type ProofStructOutput = [
    merkleProof: string[],
    body: IJsonApi.BodyStructOutput
  ] & { merkleProof: string[]; body: IJsonApi.BodyStructOutput };
}

export interface IFdcVerificationInterface extends Interface {
  getFunction(nameOrSignature: "verifyJsonApi"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "verifyJsonApi",
    values: [IJsonApi.ProofStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "verifyJsonApi",
    data: BytesLike
  ): Result;
}

export interface IFdcVerification extends BaseContract {
  connect(runner?: ContractRunner | null): IFdcVerification;
  waitForDeployment(): Promise<this>;

  interface: IFdcVerificationInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  verifyJsonApi: TypedContractMethod<
    [proof: IJsonApi.ProofStruct],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "verifyJsonApi"
  ): TypedContractMethod<[proof: IJsonApi.ProofStruct], [boolean], "view">;

  filters: {};
}
