/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAgentStaking } from "./IAgentStaking";
export type { IFastUpdater } from "./IFastUpdater";
export type { IFdcHub } from "./IFdcHub";
export type { IFdcVerification } from "./IFdcVerification";
export type { IFlareContractRegistry } from "./IFlareContractRegistry";
export type { IRandomNumberV2 } from "./IRandomNumberV2";
