/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "IERC1363",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1363__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "SafeERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SafeERC20__factory>;
    getContractFactory(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165__factory>;
    getContractFactory(
      name: "ReentrancyGuard",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ReentrancyGuard__factory>;
    getContractFactory(
      name: "AgentRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AgentRegistry__factory>;
    getContractFactory(
      name: "AgentStaking",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AgentStaking__factory>;
    getContractFactory(
      name: "FDCVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FDCVerifier__factory>;
    getContractFactory(
      name: "FlareEscrow",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FlareEscrow__factory>;
    getContractFactory(
      name: "IFDCVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IFDCVerifier__factory>;
    getContractFactory(
      name: "IFlareOrderBook",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IFlareOrderBook__factory>;
    getContractFactory(
      name: "FlareOrderBook",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FlareOrderBook__factory>;
    getContractFactory(
      name: "FTSOPriceConsumer",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FTSOPriceConsumer__factory>;
    getContractFactory(
      name: "IAgentStaking",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAgentStaking__factory>;
    getContractFactory(
      name: "IFastUpdater",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IFastUpdater__factory>;
    getContractFactory(
      name: "IFdcHub",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IFdcHub__factory>;
    getContractFactory(
      name: "IFdcVerification",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IFdcVerification__factory>;
    getContractFactory(
      name: "IFlareContractRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IFlareContractRegistry__factory>;
    getContractFactory(
      name: "IRandomNumberV2",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IRandomNumberV2__factory>;
    getContractFactory(
      name: "MockFastUpdater",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockFastUpdater__factory>;
    getContractFactory(
      name: "MockFdcVerification",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockFdcVerification__factory>;
    getContractFactory(
      name: "MockRandomNumberV2",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockRandomNumberV2__factory>;
    getContractFactory(
      name: "IAgentRegistrySync",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAgentRegistrySync__factory>;
    getContractFactory(
      name: "ReputationToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ReputationToken__factory>;

    getContractAt(
      name: "Ownable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "IERC1363",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1363>;
    getContractAt(
      name: "IERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "SafeERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SafeERC20>;
    getContractAt(
      name: "IERC165",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC165>;
    getContractAt(
      name: "ReentrancyGuard",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ReentrancyGuard>;
    getContractAt(
      name: "AgentRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.AgentRegistry>;
    getContractAt(
      name: "AgentStaking",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.AgentStaking>;
    getContractAt(
      name: "FDCVerifier",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.FDCVerifier>;
    getContractAt(
      name: "FlareEscrow",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.FlareEscrow>;
    getContractAt(
      name: "IFDCVerifier",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IFDCVerifier>;
    getContractAt(
      name: "IFlareOrderBook",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IFlareOrderBook>;
    getContractAt(
      name: "FlareOrderBook",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.FlareOrderBook>;
    getContractAt(
      name: "FTSOPriceConsumer",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.FTSOPriceConsumer>;
    getContractAt(
      name: "IAgentStaking",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IAgentStaking>;
    getContractAt(
      name: "IFastUpdater",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IFastUpdater>;
    getContractAt(
      name: "IFdcHub",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IFdcHub>;
    getContractAt(
      name: "IFdcVerification",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IFdcVerification>;
    getContractAt(
      name: "IFlareContractRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IFlareContractRegistry>;
    getContractAt(
      name: "IRandomNumberV2",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IRandomNumberV2>;
    getContractAt(
      name: "MockFastUpdater",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockFastUpdater>;
    getContractAt(
      name: "MockFdcVerification",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockFdcVerification>;
    getContractAt(
      name: "MockRandomNumberV2",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockRandomNumberV2>;
    getContractAt(
      name: "IAgentRegistrySync",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IAgentRegistrySync>;
    getContractAt(
      name: "ReputationToken",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ReputationToken>;

    deployContract(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "IERC1363",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1363>;
    deployContract(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "SafeERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SafeERC20>;
    deployContract(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC165>;
    deployContract(
      name: "ReentrancyGuard",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ReentrancyGuard>;
    deployContract(
      name: "AgentRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AgentRegistry>;
    deployContract(
      name: "AgentStaking",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AgentStaking>;
    deployContract(
      name: "FDCVerifier",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FDCVerifier>;
    deployContract(
      name: "FlareEscrow",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FlareEscrow>;
    deployContract(
      name: "IFDCVerifier",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFDCVerifier>;
    deployContract(
      name: "IFlareOrderBook",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFlareOrderBook>;
    deployContract(
      name: "FlareOrderBook",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FlareOrderBook>;
    deployContract(
      name: "FTSOPriceConsumer",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FTSOPriceConsumer>;
    deployContract(
      name: "IAgentStaking",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAgentStaking>;
    deployContract(
      name: "IFastUpdater",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFastUpdater>;
    deployContract(
      name: "IFdcHub",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFdcHub>;
    deployContract(
      name: "IFdcVerification",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFdcVerification>;
    deployContract(
      name: "IFlareContractRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFlareContractRegistry>;
    deployContract(
      name: "IRandomNumberV2",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IRandomNumberV2>;
    deployContract(
      name: "MockFastUpdater",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockFastUpdater>;
    deployContract(
      name: "MockFdcVerification",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockFdcVerification>;
    deployContract(
      name: "MockRandomNumberV2",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockRandomNumberV2>;
    deployContract(
      name: "IAgentRegistrySync",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAgentRegistrySync>;
    deployContract(
      name: "ReputationToken",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ReputationToken>;

    deployContract(
      name: "Ownable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "IERC1363",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1363>;
    deployContract(
      name: "IERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "SafeERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SafeERC20>;
    deployContract(
      name: "IERC165",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC165>;
    deployContract(
      name: "ReentrancyGuard",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ReentrancyGuard>;
    deployContract(
      name: "AgentRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AgentRegistry>;
    deployContract(
      name: "AgentStaking",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AgentStaking>;
    deployContract(
      name: "FDCVerifier",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FDCVerifier>;
    deployContract(
      name: "FlareEscrow",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FlareEscrow>;
    deployContract(
      name: "IFDCVerifier",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFDCVerifier>;
    deployContract(
      name: "IFlareOrderBook",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFlareOrderBook>;
    deployContract(
      name: "FlareOrderBook",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FlareOrderBook>;
    deployContract(
      name: "FTSOPriceConsumer",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FTSOPriceConsumer>;
    deployContract(
      name: "IAgentStaking",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAgentStaking>;
    deployContract(
      name: "IFastUpdater",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFastUpdater>;
    deployContract(
      name: "IFdcHub",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFdcHub>;
    deployContract(
      name: "IFdcVerification",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFdcVerification>;
    deployContract(
      name: "IFlareContractRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFlareContractRegistry>;
    deployContract(
      name: "IRandomNumberV2",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IRandomNumberV2>;
    deployContract(
      name: "MockFastUpdater",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockFastUpdater>;
    deployContract(
      name: "MockFdcVerification",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockFdcVerification>;
    deployContract(
      name: "MockRandomNumberV2",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockRandomNumberV2>;
    deployContract(
      name: "IAgentRegistrySync",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAgentRegistrySync>;
    deployContract(
      name: "ReputationToken",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ReputationToken>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
