/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAgentRegistrySync,
  IAgentRegistrySyncInterface,
} from "../../../contracts/ReputationToken.sol/IAgentRegistrySync";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "agent",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "reputation",
        type: "uint256",
      },
    ],
    name: "syncReputation",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IAgentRegistrySync__factory {
  static readonly abi = _abi;
  static createInterface(): IAgentRegistrySyncInterface {
    return new Interface(_abi) as IAgentRegistrySyncInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IAgentRegistrySync {
    return new Contract(address, _abi, runner) as unknown as IAgentRegistrySync;
  }
}
